### ISSUE TITLE
Simple Tabs Alt Restyle

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#137]
I would like to add an active top border to the simple-tabs-alt component so that it reinforces what view you are currently on other than the subtle background color.

Currently:
![image](https://cloud.githubusercontent.com/assets/4721717/6110155/eecade7e-b04d-11e4-903d-a62dae63a89b.png)

Requested:
![image](https://cloud.githubusercontent.com/assets/4721717/6110176/ff3f7382-b04d-11e4-9303-8bc611510974.png)

**Comment by atomanyih** [comment]
I believe this has been done
