### ISSUE TITLE
Collapse react component should accept className prop

### ISSUE THREAD

**Issue by pmeskers** [pivotal-cf/pivotal-ui#157]
We're trying to have something like this...

```
<UI.Collapse className='foo'>
    ....
</UI.Collapse>
```

where the `foo` class would be added to the top-level `.panel` div.

**Comment by pmeskers** [comment]
More generally, we don't know how to nest different styles in this component. 

In the HTML/CSS/Bootstrap way of collapses, we had style like this:
![screen_shot_2015-06-03_at_4 10 45_pm](https://cloud.githubusercontent.com/assets/693476/7985968/8f867dc4-0aa2-11e5-90b7-df94dc4aee79.png)

But it involves lots of margin and padding adjustments to the various panels/panel-body/panel-headings. Not sure what the best way to accomplish this would be via UI.Collapse.

**Comment by gpleiss** [comment]
We've captured this request in the following story: https://www.pivotaltracker.com/story/show/96201832

**Comment by stubbornella** [comment]
I've prioritized this story, it should get worked on this week or next.

**Comment by ctaymor** [comment]
This was fixed in 9002d2324296d282ce832ad3a974e92f1ba6422b and is a part of the new 2.0.0-alpha release.
