### ISSUE TITLE
Update CONTRIBUTING docs 

### ISSUE THREAD

**Issue by pmeskers** [pivotal-cf/pivotal-ui#162]
Hey,

We are trying to work on updating the AlertNotification react component, but it's unclear what the best/intended practice is for doing this.

Now that the react components are part of the main repository, I thought perhaps the styleguide would serve components that were prepared locally, but it looks like it actually still uses the remote npm releases in `src/pivotal-ui/javascripts/components.js`. 

We thought to change that components file to require the local JS file (e.g., `  Notifications: require('../../pivotal-ui-react/notifications/notifications.js').Notifications`), but when running the default gulp task it does not preprocess the react components (since it assumed them to be coming from node modules, and therefore already transpiled). 

Unfortunately, the CONTRIBUTING readme does not talk about what the current build and development process is for working on react components. It would be great if this were updated so other teams had a clear path for making contributions. 

Cheers!

**Comment by gpleiss** [comment]
Yeah, the contributing docs are out of date. Right now, we are working on making the developer workflow much easier, and we'll update the docs when we're done.

In the meantime, what you can do:

* Run `gulp react-build`
* Run `npm link dist/react/<REACT_COMPONENT>`
* Restart the server

This symbolically links `node_modules/pui-react-<REACT_COMPONENT>` to the transpiled local version.

Sorry you've had so much pain related to contributing! It should get better soon :grin:

**Comment by gpleiss** [comment]
They've been updated, and the contributor flow is much better now. Enjoy!
