### ISSUE TITLE
Modal should vertically scroll on small viewports

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#163]
Currently if the viewport is too small vertically and the modal's content is too large, a user cannot scroll to view the action buttons in the footer of the modal (In PivNet's case it's the Accept and Download button).

![image](https://cloud.githubusercontent.com/assets/4721717/8111347/45de9d5e-102f-11e5-8157-b4c02ca1e40c.png)

Ideally, the header and footer would be fixed and only the content would scroll:
![image](https://cloud.githubusercontent.com/assets/4721717/8111456/f86412e2-102f-11e5-9951-4cfadbdb10ca.png)

**Comment by gpleiss** [comment]
So - the modal height should be a fixed value on larger screen, and `screen-height - 2*header_margin` on smaller screens. Is that right?

**Comment by gpleiss** [comment]
This may also have to be a PR to bootstrap

**Comment by pivotal-plech** [comment]
I think the modal should have a reasonable percentage height with a `max-height`, so that it doesn't look ridiculous on tall viewports...which I think is what you are saying.

We would also have to provide a viewport (overflow-y: scroll/auto) on the `modal-body` to ensure that users can scroll on small screens...we have some people on MBAirs.

Oh, fun. Let's get some bootstrap cred.

**Comment by pmeskers** [comment]
```
.modal .modal-dialog {
  height: 100%;
}

.modal .modal-content {
  max-height: 90%;
  overflow-y: auto;
}
```

Is what we just added to PivNet this morning -- In situations where the user has a large enough browser where they wouldn't need to scroll, they see no modal scrollbar. When the user has a small viewport, it will add a scrollbar for overflow-y.

**Comment by bebepeng** [comment]
Interesting thing is this isn't a problem on the non-react component. @pivotal-plech @gpleiss @pmeskers

**Comment by gpleiss** [comment]
Hmm... this may be a problem with React Bootstrap then.

@pmeskers - so if that styling fixes the height issue for react modals, does it affect non-react modals? If not, then we can probably throw that css in PUI and fix the issue.

If you have a solution, we'd appreciate a PR! (We're about to fix our CSS development/contribution flow, so a CSS PR should be pretty easy).

**Comment by rdy** [comment]
a better way to set the height of the modal would be to use viewport height units.
http://caniuse.com/#feat=viewport-units

**Comment by stubbornella** [comment]
I'd rather go back to the (working) non-react bootstrap way of managing modal height... I'm not sure what the bootstrap-react component changed, but it seems like something we should fix in a PR rather than just a bandaid.

**Comment by stubbornella** [comment]
@rdy vh aren't well supported on IOS7. They use the document height rather than the viewport.

**Comment by gpleiss** [comment]
@stubbornella as in PR to react-bootstrap?

**Comment by stubbornella** [comment]
@gpleiss yes, the modal is working well in normal BS js.

**Comment by stubbornella** [comment]
I added a story to our backlog.

**Comment by atomanyih** [comment]
I think this has been addressed
