### ISSUE TITLE
A quick fix for pivotal-ui-react/radio-group.js

### ISSUE THREAD

**Issue by averykimball** [pivotal-cf/pivotal-ui#166]
RadioGroup wasn't passing the onChange prop to it's children- the cloneWithProps was referencing onChange local to Radio's context (which resulted in undefined).  I made this change:

Line 48:

    children = React.Children.map(children, (child) => cloneWithProps(child, {name, onChange: this.onChange}));

==>

    children = React.Children.map(children, (child) => cloneWithProps(child, {name, onChange: this.props.onChange}));
                                                                                                  ^^^^^^^
Now everything works on tin.

EDIT: So I'm thinking of forking this as there is another thing I feel could be fixed in this (the inclusion of id in the second argument of cloneWithProps, which fulfills the intention of Radio-Group to pass it's id prop to it's children).

**Comment by stubbornella** [comment]
@averykimball - Thanks! We'll take a look.

@gpleiss - I opened a story in our backlog to take a look at this.

**Comment by gpleiss** [comment]
@averykimball can you provide an example where `onChange` isn't working?

On our [styleguide's radio group example](http://styleguide.pivotal.io/react_beta.html#form_radio_input_react), the `onChange` event properly bubbles down to each radio input. (This works, with the way the code currently is).

**Comment by gpleiss** [comment]
@averykimball as far as bubbling down the `id` property - is there a specific use case you have in mind? `id`s have to be unique in html. We'll have html problems if each radio button gets the same id as the radio group.

**Comment by averykimball** [comment]
Hi! So my use-case was a hacky onChange/onBlur expose of another form, where I was passing references to other components at the Radio level; I was completely misusing the RadioGroup, and when I started looking at what changes I would make to your codebase, I realized the way I wanted to do my conditional render was just awful and I shouldn't touch your nice, stable code. 

So I cried a little and forgot about it. Thanks for your time and for considering my issue, though!

**Comment by gpleiss** [comment]
:smile:
