### ISSUE TITLE
 Safari Sortable List Doesn’t Work (Number.isNaN is not defined, easy fix)

### ISSUE THREAD

**Issue by jacobp100** [pivotal-cf/pivotal-ui#171]
Either use isNaN, or polyfill Number.isNaN. Can confirm that after polyfilling (`typeof x === 'number' && isNaN(x)`), this does work.

**Comment by stubbornella** [comment]
@jacobp100 - we'd be open to a PR for this, do you want to submit one?

**Comment by gpleiss** [comment]
@jacobp100 sorry - are you referring to our React Sortable List component?

**Comment by jacobp100** [comment]
No, the sortable list, where you can drag and drop items to rearrange.

**Comment by jacobp100** [comment]
To correct my comment, it’s a “draggable” list. Specifically https://github.com/pivotal-cf/pivotal-ui/blob/99338243aa04b04f745ee5a9f60ed5e7bc2c2290/src/pivotal-ui-react/draggable-list/draggable-list.js#L88

**Comment by nicw** [comment]
Heya @jacobp100 we've fixed this in our new 2.0 release. The alpha is available via npm:  npm install pui-react-draggable-list --save
