### ISSUE TITLE
React Typeahead Time Select Dropdown

### ISSUE THREAD

**Issue by DougBlumeyer** [pivotal-cf/pivotal-ui#174]
React Component for quickly selecting a time by hour in the dropdown, while also having the power to type the time in directly in the main field.

![screen shot 2015-06-30 at 11 21 50 am](https://cloud.githubusercontent.com/assets/4460669/8438375/47962c94-1f1a-11e5-9379-35fd68db9e7c.png)

Specs:
1. Customizable default time options.
2. The rounded hours are sorted descending (backwards in time)
3. Clicking on the field opens the dropdown.
4. Using arrow keys should navigate the dropdown, highlighting selection
5. Pressing return should select the highlighted selection
6. Type ahead filters for matching hours (Typing "9" should match "9:00:00 AM" and "9:00:00 PM" Typing "9:3" should not match anything)
7. (Ideal) Tab autocompletes what is identical among all matches. For example, if you type "9" and then push tab, it will autocomplete to "9:00:00", so you can go straight to typing either "A" or "P".
8. The dropdown defaults to a time which is not rounded to the nearest hour, but which is a snapshot of the time the moment the component is built.
9. Another dynamic option for "now". 
   * When now is selected, "now" remains an option in the dropdown, but the snapshot option is updated/replaced with the new snapshot. 
   * For example, if it's 3:45:23 PM when I first encounter the component, so that's the default option above "now" (and hours counting backwards from 3:00:00 PM). If I wait five seconds and select "now" in the dropdown, then the newly displayed time should be "3:45:28 PM" and "3:45:23 PM" should no longer be listed.
   * Subtle grey divider lines separate the "now" option from the rounded hours below and the current time snapshot above:

![screen shot 2015-06-30 at 11 22 46 am](https://cloud.githubusercontent.com/assets/4460669/8438403/732eac1e-1f1a-11e5-85ce-e08b91c74e79.png)

**Comment by pivotal-plech** [comment]
@DougBlumeyer Is there a prototype or an example that does this already that has the existing functionality. I'm having a hard time understanding the interaction through reading the specs.

Thanks!

**Comment by scottruitt** [comment]
@pivotal-plech no prototype, afaik. think of it as a dropdown with a custom option that's typed inline, and then throw in some auto-complete magic on top.

**Comment by DougBlumeyer** [comment]
No prototype. Sorry the specs weren't easy enough to follow. Happy to talk through them with you and supplement.

**Comment by nicw** [comment]
Closing this per @pivotal-plech. This type of item isn't meant for the styleguide, and is best for the individual product team to implement.
