### ISSUE TITLE
React Typeahead Tree Structure Dropdown

### ISSUE THREAD

**Issue by DougBlumeyer** [pivotal-cf/pivotal-ui#175]
A search + dropdown for selecting items nested in a hierarchy. 

![screen shot 2015-06-30 at 11 54 45 am](https://cloud.githubusercontent.com/assets/4460669/8439143/d7901acc-1f1e-11e5-9ea4-4e79ee99b4fe.png)

Specs:
1. Filter options by searched string. All children and all parents of matched items are still shown (not filtered out)
2. Dropdown maxes at a certain number of displayed items and has a scroll for vertical overflow. Widens to fit horizontal overflow.
3. Indentations identify levels of the hierarchy. Lowest level items have a white background; higher level items have a greyed background.
4. Bold + underline the matching substrings in each of the matched items.
5. The first matched item is automatically selected. Arrow keys then move the highlighted-background selection, and return key selects it.
6. Clicking the arrow on the right edge expands the dropdown, showing all available options (no filtering), without having to start typing.

Relevant code (we began developing this component for Pivotal Pulse already):
https://github.com/pivotal-cf/pivotal-ui-charts/blob/master/app/components/app_search.js
https://github.com/pivotal-cf/pivotal-ui-charts/blob/master/app/components/search_list.js
https://github.com/pivotal-cf/pivotal-ui-charts/blob/master/app/components/search_list_item.js

**Comment by nicw** [comment]
Closing this per @pivotal-plech. This type of item isn't meant for the styleguide, and is best for the individual product team to implement.
