### ISSUE TITLE
Neutral Color Swatches should have a consistent naming schema

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#203]
Currently all of the colors provided by Pivotal UI have a consistent naming schema except for the grays.

For example:
```
$gray-2
.bg-neutral-2
.type-neutral-2

vs

$dark-2
.bg-dark-2
.type-dark-2
```

I would think that the gray color variable `$gray-2` should probably be `$neutral-2`.

**Comment by pivotal-plech** [comment]
The drive behind this is to clean up the interface a bit so we don't have to include tiny type for each color swatch. I think a better interface would be the stand alone color swatches with a name ex: `neutral-2`, and then simply provide some copy above the watches informing the user that they could use background or type modifiers with the color name.

Better yet, it would be amazing if there could some form of just selecting the color to copy it to the clipboard! Wow!!

**Comment by ctaymor** [comment]
Looks like the color variables got changed in 2.0.0-alpha. Is this still an open issue with 2.0.0-alpha?

**Comment by nicw** [comment]
Heya @pivotal-plech, any thoughts on Caroline's comment?

**Comment by pivotal-plech** [comment]
No this should be deleted.
