### ISSUE TITLE
Current List Item in "Steps" List Element appears disabled

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#204]
Currently the current steps element does not look current; it looks more like it's disabled.
![image](https://cloud.githubusercontent.com/assets/4721717/8726970/3083abba-2bab-11e5-870b-1c21b3b71b33.png)

I would suggest something like the following:
![image](https://cloud.githubusercontent.com/assets/4721717/8727035/853bfce8-2bab-11e5-8a40-6efbf5d5a913.png)

**Comment by ctaymor** [comment]
This is fixed in 2.0.0 (which is currently released and available as 2.0.0-alpha.0).
