### ISSUE TITLE
React-Bootstrap co-team collaboration

### ISSUE THREAD

**Issue by mtscout6** [pivotal-cf/pivotal-ui#231]
I wasn't able to find another medium upon which to reach out to your team so I hope this is sufficient. First off I'd like to express my appreciation along with the gratitude from the React-Bootstrap team for your efforts to enhance our accessibility and public API. 

Per our team's model for [maintenance](https://github.com/react-bootstrap/react-bootstrap/blob/master/MAINTAINING.md#becoming-a-maintainer) we have expressed that when we see devoted individuals continually providing support we will extend an invitation to join the organization. Though your team's case is particularly interesting since we are seeing a devoted team helping out.

Before we started reaching out to individual members of your team to see if they'd like to join we thought it may be more beneficial to first reach out to your team as a whole and ask if you have one to three members that you feel would be the best fit.

With that said the two teams are slightly different in the way that we approach things, and our focus is different from one another. At the same time we don't want to see that we are preventing you from moving forward. We are open to new tools or governance that will aid in the development lifecycle of our packages, so if there's something that you wish to change just open an issue and we can discuss it as a team. We follow a majority rule governance, and silence is usually perceived as acceptance given a reasonable period of time to allow all interested parties to respond.

Our initial process for adding collaborators is first to permit new members to review and accept pull requests. Then after we see that things are working well we have traditionally given push access to npm primarily for those that show senior level traits. We haven't documented this quasi promotion system, but it has been what we've done so far.

Please take a moment to review our [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) and [Maintaining](https://github.com/react-bootstrap/react-bootstrap/blob/master/MAINTAINING.md) documentation and let us know if this works for you, or if you are interested. It is our sincere hope that our two teams can work together to build rich reusable components.

On a side note it may make sense in some cases to breakout a new library similar to what we are doing with the react-overlays and react-prop-types projects. If something like this is identified we are open to discussion about it.

/cc 
react-bootstrap team:
@aabenoja @AlexKVal @dozoisch @joemcbride @jquense @mathieumg @mfunkie @taion

pivotal team we've seen:
@atomanyih @ctaymor @gpleiss @kennyw12 @matt-royal @nicw @stubbornella

**Comment by AlexKVal** [comment]
:+1: :tada:

**Comment by mathieumg** [comment]
:cherries: :sparkles: :+1:

**Comment by dozoisch** [comment]
:+1:

**Comment by atomanyih** [comment]
:ok_woman:  :confetti_ball: 

Thanks! This is awesome news; we anticipate more work with react-bootstrap in the future and we'd love to work more closely with yall. 

It would be great to have a conversation about what this means on a more specific level. Maybe we can set up a conference or video call sometime soon?


The Pivotal UI Team - pivotal-ui@pivotal.io
@atomanyih @ctaymor @d-reinhold @kennyw12 @matt-royal @nicw @stubbornella

**Comment by mtscout6** [comment]
If everyone can say when they are available then we can pick a time to meet: http://doodle.com/7x25rr29mygr2gr3 either after everyone says when they are available or by Monday mid-day I'll pick a time from the survey for the meetup. Does that sound reasonable to everyone?

**Comment by mtscout6** [comment]
Also for all those interested if you can share your email address with me by emailing mtscout6@gmail.com (I know some folks don't share they email address on github), then I can send a calendar invite when it's scheduled.

**Comment by ctaymor** [comment]
Sounds good. We added the times we're available to the doodle.

We're in a different timezone (PST), and mornings are hard for us anyways, so if doing it later in the day is a possibility, that would open up a lot more time slots on our end in addition to the limited times we put on the doodle.

The Pivotal UI Team - pivotal-ui@pivotal.io
@atomanyih @ctaymor @d-reinhold @kennyw12 @matt-royal @nicw @stubbornella

**Comment by mtscout6** [comment]
The survey results are in, I'll be sending out an online calendar invite for Wed. Aug. 19th at 11:00 AM MDT. (I'm pretty sure that's 10:00 AM PST)

**Comment by mtscout6** [comment]
I sent out the calendar invite. I was only able to send it to those of you that have your email publicly visible on GitHub, please either forward the invite to anyone interested that you don't already see listed. Or anyone can feel free to shoot me an email at mtscout6@gmail.com and I'll add you to the invite list.

**Comment by atomanyih** [comment]
@mtscout6 Thanks for organizing this!

If you throw an invite towards the team email (pivotal-ui@pivotal.io) it should invite everyone.

**Comment by mtscout6** [comment]
@atomanyih I just sent it to that group.

**Comment by mtscout6** [comment]
For anybody that missed the meeting invite the url to join the google Hangout is: https://plus.google.com/hangouts/_/calendar/bXRzY291dDZAZ21haWwuY29t.hr0575svgckea0pgvcbhvj3l9o

Should be starting in a few minutes.

**Comment by atomanyih** [comment]
@mtscout6 

It was great to talk to you all earlier! Here's the list of github usernames for our team:
@atomanyih @kennyw12 @ctaymor @d-reinhold

**Comment by mtscout6** [comment]
Invitations have been sent!

**Comment by mathieumg** [comment]
Welcome aboard, you seemed like a dynamic bunch on Hangout! :grin:
