### ISSUE TITLE
Dropdown list of React components is too long to fit on a 13" Macbook Pro

### ISSUE THREAD

**Issue by d-reinhold** [pivotal-cf/pivotal-ui#248]
![screen shot 2015-09-08 at 1 38 01 pm](https://cloud.githubusercontent.com/assets/815285/9746813/e46208ea-562e-11e5-88b2-45e99728001d.png)

I can't see Tabs, Tooltips, or Typography..

**Comment by nicw** [comment]
Thanks @d-reinhold - we'll look into this w/ @pivotal-plech when we discuss rearranging those React components.
