### ISSUE TITLE
Autocomplete doesn't work in Safari

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#256]
In Safari Version 8.0.4 (10600.4.10.7), clicking on an autocomplete list item doesn't trigger a callback. #253 Fixed this issue for firefox, but Safari is weird.

**Comment by nicw** [comment]
Didn't we fix this w/ https://www.pivotaltracker.com/story/show/103153540 ?

**Comment by nicw** [comment]
@atomanyih

**Comment by atomanyih** [comment]
nah, I think they only fixed firefox

**Comment by rdy** [comment]
Could we look into a fix for Safari? It might be possible to use the "this" inside the event handler to get the right target.

**Comment by atomanyih** [comment]
@rdy I'll leave it to you

**Comment by charleshansen** [comment]
I saw the pull request #349, it breaks hiding the autocomplete list in Chrome and Firefox.

**Comment by charleshansen** [comment]
Finally fixed, will be in 4.0
