### ISSUE TITLE
Typography Header Colors are !important are they really?

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#257]
As is, consumers of PUI can't change the colors of their headings without making really gross css. Is type-dark-2 on headers really that important?

**Comment by pivotal-plech** [comment]
I agree that `MarketingH1` should have it's own styles that you should be able to overwrite in exceptional circumstances.

However, I think that all modifier classes (background, type, whitespace) should have !important as they need to have a predictable level of specificity necessary to actually work. Modifier classes should always work when you apply them to elements.

**Comment by atomanyih** [comment]
so the solution: change our typography classes to not use modifiers classes, instead use the same variables?

**Comment by pivotal-plech** [comment]
Yeah, that makes a lot of sense.
