### ISSUE TITLE
react-boostrap is fully included in most components

### ISSUE THREAD

**Issue by rdy** [pivotal-cf/pivotal-ui#258]
In a lot of components we are doing this:
```
var BsAlert = require('react-bootstrap').Alert;
```

But we want to be doing this:
```
var BsAlert = require('react-bootstrap/lib/alert')
```

We don't want to use the full react-bootstrap require since that brings in about 600k of javascript into projects that have pivotal-ui as a dependency.

It would be great to fix this before we get many projects to switch to 2.0.

**Comment by atomanyih** [comment]
a2847f9b2793b9770db8e8eb9627c857f928ecf1 :wink:

**Comment by rdy** [comment]
Looking good
