### ISSUE TITLE
Search Functionality on Styleguide is missing

### ISSUE THREAD

**Issue by stupakov** [pivotal-cf/pivotal-ui#262]
There should be a search function for the styleguide. Without the `All` page, it is currently hard to find something specific when you don't know where it lives on the styleguide.

**Comment by atomanyih** [comment]
It's an unfortunate drawback of the new layout, but I'm sure @pivotal-plech will cook up something good for the future.

For now here's a top-secret tip for those in the know: http://styleguide.pivotal.io/react_all.html or http://styleguide.pivotal.io/css_all.html

**Comment by pivotal-plech** [comment]
@atomanyih I can easily add an all style, but is it possible to dog-food our own `FilteringSearchExample` component and use that as a way to quickly find any Element, Component or Modifier?

**Comment by atomanyih** [comment]
ooooo that's a fun idea and I think totally doable

**Comment by atomanyih** [comment]
If you mock it up I can try to make it so

**Comment by pivotal-plech** [comment]
mocking as i type

**Comment by atomanyih** [comment]
:no_good: don't mock me :no_good:

**Comment by nicw** [comment]
I'm closing this out - it's in the designers backlog, where it needs to be mocked up and tested.
