### ISSUE TITLE
When click is held down over a drop down, the text becomes highlighted

### ISSUE THREAD

**Issue by questionmarc** [pivotal-cf/pivotal-ui#263]
**Priority:** P5
**Problem:** The highlighted text isn't aesthetically pleasing
**Pictures:**
![pivotal_network_normal](https://cloud.githubusercontent.com/assets/1682054/10376223/b2a89766-6dca-11e5-9c5c-d224ef1544ef.png)
![pivotal_network_hold_down_click_on_dropdown](https://cloud.githubusercontent.com/assets/1682054/10376224/b47e9de2-6dca-11e5-8100-a3ce22ba1040.png)

**Comment by atomanyih** [comment]
@questionmarc this is now available in 2.1.0-alpha.0 :tada:
