### ISSUE TITLE
Error: Cannot find module 'pui-react-helpers'

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#265]
When I try to install grids:
`npm install pui-react-grids --save`

And include the components in the app:
```
var Row = require('pui-react-grids').Row;
var Col = require('pui-react-grids').Col;
```

I get the error:
`Error: Cannot find module 'pui-react-helpers'`

Simply installing `pui-react-helpers` fixes it, but it would be nice if that was documented or if it were just a dependency in `pui-react-grids`...

@atomanyih @nicw

**Comment by atomanyih** [comment]
@kennyw12 actually fixed this in #259, but we haven't pushed out a new version yet :person_frowning:
