### ISSUE TITLE
Responsive Tabs

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#266]
Tabs should have the ability to turn off responsiveness.

There should be a way to add a className/id to the React BS Tabs/Accordion component within the responsive PUI Tabs. 

responsiveBreakpoint is not intuitive and doesn't actually work as intended. 
ie: `responsiveBreakpoint={md}` renders Tabs in small screens and large screens.

**Comment by atomanyih** [comment]
fixed in: 05418c94a182040bd161802d51c1e3ae483b07ef
