### ISSUE TITLE
React Panels Footer Feature

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#268]
CSS Panel examples have footers. React Panels should have this feature too?

**Comment by charleshansen** [comment]
story prioritized https://www.pivotaltracker.com/story/show/105361948

**Comment by atomanyih** [comment]
added: https://github.com/pivotal-cf/pivotal-ui/commit/1615468ed42b64a77ba64582349ed5b34ce31bb9
