### ISSUE TITLE
Remove Padding From Alerts and TabPanes

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#269]
Alerts and Tab-panes have extraneous padding that is annoying to work with. These should be styleguide only css rather than being published.

**Comment by pivotal-plech** [comment]
@kennyw12 What do you mean by extraneous? Could you attach an image perhaps?

I think this may be similar to a request to add whitespace modifiers to the `.tab-pane` within tabs. Would that solve your problem?

**Comment by atomanyih** [comment]
@kennyw12 does this also relate to #274?

**Comment by kennyw12** [comment]
@atomanyih Yes, the Alerts relates to #274 in that the padding comes from bootstrap, but the [margin](https://github.com/pivotal-cf/pivotal-ui/blob/development/src/pivotal-ui/components/alerts/alerts.scss#L164) is also annoying and it comes from PUI.

![screen shot 2015-10-14 at 12 51 19 pm](https://cloud.githubusercontent.com/assets/1689040/10495782/7d449b22-7272-11e5-8ead-0baf20ee91a6.png)


@pivotal-plech These huge images might be helpful. The whitespace modifiers are a solution but it would mean that I would have to use the modifiers to get rid of padding which is a bit strange?
The `.tab-pane` class in PUI provides the [padding](https://github.com/pivotal-cf/pivotal-ui/blob/development/src/pivotal-ui/components/tabs/tabs.scss#L251).

These CSS declarations should live in styleguide.scss and not affect consumers?

![screen shot 2015-10-14 at 12 54 52 pm]
(https://cloud.githubusercontent.com/assets/1689040/10495902/1797b6d2-7273-11e5-8a86-e082e109f3fb.png)

**Comment by atomanyih** [comment]
@kennyw12 I'm with you that the leading and trailing margins (on alerts and panels, respectively) are lame.

I don't have a problem with the internal padding but I could be convinced otherwise.

IMO it's reasonable to have *sane* defaults so tabs and panels look nice out of the box. Inner padding gives us this, weird margins do not

**Comment by nicw** [comment]
Closing this out: We have a separate story for just removing the margins. You can currently override margins and padding with whitespace classnames.
