### ISSUE TITLE
OverlayTrigger doesn't allow custom triggers.

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#270]
It would be nice if OverlayTriggers allows more custom ways to trigger overlay visibility. 
ie `showOverlay={true}`

**Comment by charleshansen** [comment]
We attempted to create a manual overlay trigger. Getting the manual triggering part is easy enough, but getting the correct positioning requires re-implementing a large amount of React-Bootstrap. We would certainly accept a pull request that had both the manual trigger and the pull request, but I don't think we have time to implement this ourselves in the near future.

**Comment by charleshansen** [comment]
Fixed in a1ea1aab964eef7f3009c7a0cb33e4bdd84b8b5b, will be available in 4.0
