### ISSUE TITLE
allow dropdown to take custom toggles

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pivotal-ui#276]
So we can do stuff like on apps manager
![screen shot 2015-10-14 at 12 39 13 pm](https://cloud.githubusercontent.com/assets/2305345/10495417/9a4b4402-7270-11e5-9f80-b575f70bb4d9.png)
 (the text on the left is a link that doesn't trigger the dropdown)

**Comment by pivotal-plech** [comment]
@atomanyih This would also be extremely useful for Collapse components as that was the original design for the styleguide.

**Comment by charleshansen** [comment]
done, in 4.0
