### ISSUE TITLE
clickable panel should be more useful, provide clicking utility

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pivotal-ui#279]
Right now, to really make a clickable panel clickable, you have to provide an onClick callback yourself.
However, if you click an `a` tag within the panel, it will follow the link *and* trigger the onClick.

To get around this you have to do something like this:

```js
function handleClick(e) {
  if(e.target.nodeName == 'A') return;
   
  doSomething();
  e.preventDefault();
}
```

Clickable panel should do this for you

**Comment by charleshansen** [comment]
This seems too custom and I'm not even sure how to do this correctly. It looks like AppsManager isn't using this anymore, so I'm going to close the issue.
