### ISSUE TITLE
license is not clear

### ISSUE THREAD

**Issue by QuoQue** [pivotal-cf/pivotal-ui#282]
pivotal-ui/LICENSE is MIT but that's contradicted by README.md and http://styleguide.pivotal.io/ which say "Copyright 2015 Pivotal Software, Inc. All Rights Reserved."

Can you clarify whether pivotal-ui is open for re-use on MIT terms?

**Comment by atomanyih** [comment]
@nicw this one's for you

**Comment by nicw** [comment]
@QuoQue sorry for the confusion. The license is indeed MIT.
