### ISSUE TITLE
Add Pivotal UI Examples to Docs

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#283]
From Robbie Clutton:
"What happened to the full examples that used to be on the site? Want to rip some off =)"

Would be easy to add links to full-site examples back to the home page for people to copy pasta.

**Comment by atomanyih** [comment]
I don't think I ever saw those. Is this like links to run.pivotal.io etc?

**Comment by pivotal-plech** [comment]
You mean you never had the pleasure of seeing Pivotal Gary?!

**Comment by pivotal-plech** [comment]
http://pivotalui-examples.cfapps.io/gary

**Comment by atomanyih** [comment]
oh my

**Comment by atomanyih** [comment]
closing bc #292
