### ISSUE TITLE
allow panels to have full headers instead of just titles

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pivotal-ui#285]
then we could do stuff like this:

![screen shot 2015-10-20 at 4 46 53 pm](https://cloud.githubusercontent.com/assets/2305345/10624097/343916f6-774a-11e5-965b-adc25845f030.png)

the top-most part of the panel (with icon and name and everything) would be the header

maybe this could be a thing? @pivotal-plech

**Comment by pivotal-plech** [comment]
@atomanyih 

Yep, I totally agree. It would be great if you could have a custom panel title and optionally add in the title parameter if it's a really simple panel.

APM does something similar (but is also putting tabs in a panel...woah) that could benefit from a custom header:
![image](https://cloud.githubusercontent.com/assets/4721717/10640833/8bc55534-77e4-11e5-8af1-e1c7a0fd4fa0.png)

---

This might be a separate issue but I've also found that we're designing the same custom panel component a lot in PivNet and see patterns in AppsMan as well.

![image](https://cloud.githubusercontent.com/assets/4721717/10641278/8bb71648-77e6-11e5-86a2-53af96379208.png)

![image](https://cloud.githubusercontent.com/assets/4721717/10641281/8eff4c08-77e6-11e5-964a-571446b8102f.png)

![image](https://cloud.githubusercontent.com/assets/4721717/10640769/2003fd64-77e4-11e5-8ddd-b15dc9e931fd.png)

It would be really nice to have Optional Parameters to pass through:
- Title
- Sub-Title (Description)
- Actions

**Comment by charleshansen** [comment]
Fix will be published in 3.0.0-alpha.2
