### ISSUE TITLE
Button Group Example shouldn't be `btn-group-large`

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#286]
The use-case for using button groups is generally to reduce noise in a complicated app. It's weird to make the example default large as most of the time you're trying to reduce the amount of white space user actions take up in the interface.

Current:
![image](https://cloud.githubusercontent.com/assets/4721717/10640285/17076a4a-77e2-11e5-82c9-1ab3ad9f18c9.png)

Desired:
![image](https://cloud.githubusercontent.com/assets/4721717/10640278/0e00d71a-77e2-11e5-9d3e-e0e4290ee981.png)

**Comment by atomanyih** [comment]
[one step ahead of you](http://styleguide-staging.cfapps.io/css_base_button-group.html) :stuck_out_tongue_winking_eye:

**Comment by pivotal-plech** [comment]
so awesome-sauce
