### ISSUE TITLE
Text Inputs and Text Areas should not have boxshadow

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#289]
All of our text-inputs and text areas got a box-shadow in PUI 2.0. I think it may have been due to adding a box-shadow to dropdowns but it was never intended to have it on all form elements.

Current:
![image](https://cloud.githubusercontent.com/assets/4721717/10642270/d2d7b0e2-77ea-11e5-9a97-10d0565dee49.png)

Desired:
![image](https://cloud.githubusercontent.com/assets/4721717/10642260/ca4bee34-77ea-11e5-8abe-53463a977864.png)

**Comment by atomanyih** [comment]
@pivotal-plech I also removed the weird dark active state for things other than selects
