### ISSUE TITLE
flexbox-based grid

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pivotal-ui#290]
@rdy wants this for reasons

**Comment by pivotal-plech** [comment]
I do for reasons as well but IE9 is the bottleneck.

**Comment by atomanyih** [comment]
We support IE9?

**Comment by rdy** [comment]
This is partially true, but I think that some of our big applications like app manager use angular which does without some additional hacks, is it possible for us to re-visit our support of IE9?

IE9 is now 4 revisions older than the latest version of IE available today. IE9 only can be installed from Windows 7 and older, although it's actually packaged with newer versions of IE if you run the service packs.

It is a bit of a shame to not move forward on some potentially useful layout components for these reasons.

**Comment by atomanyih** [comment]
apparently with new bootstrap you can use the grid with flexbox:

http://v4-alpha.getbootstrap.com/getting-started/flexbox/

**Comment by rdy** [comment]
when are we upgrading to the new bootstrap?

**Comment by jadekler** [comment]
This is currently in progress and has been broken out into separate stories with the `8pt-grid` label: https://www.pivotaltracker.com/n/projects/1126018
