### ISSUE TITLE
traffic lights should color the text

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pivotal-ui#291]
@pivotal-plech 

AppsMan has this:
![screen shot 2015-10-21 at 11 24 26 am](https://cloud.githubusercontent.com/assets/2305345/10646140/66621b7c-77e6-11e5-91cb-319ab12cf643.png)

Alternately, maybe traffic lights CSS should live in the AppsMan codebase?
Is anyone else using it? I thought I might have seen it on APM? @rdy

**Comment by pivotal-plech** [comment]
I'm not convinced this particular component is reusable outside AppsMan. We do use the dots to communicate state in APM, but the component is specific to a 'space' at the moment which I believe is only exposed in a UI in AppsMan.

**Comment by atomanyih** [comment]
That makes sense. I'd like to remove it from PUI at some point but I'll close this issue for now
