### ISSUE TITLE
make modal a wrapper around react-bootstrap's modal

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pivotal-ui#296]
It's better and the animations are smoother. It also fixes the problem with the body changing size

I spiked on swapping out the implementation and it was overall pretty easy and looked identical, except for smoother transitions.

Only problem is the html changes, so a lot of our tests break. It also changes the API slightly, in that we can't add classes to the same stuff.

For whatever reason, we put the prop `className` on the modal content div instead of the modal dialog itself. With the react-bootstrap one we can't access that div, but do we even want it?

**Comment by pivotal-plech** [comment]
Yeah the `modal-content` isn't really important as it doesn't have any default padding on it. The only div that I would like to be able to pass modifiers to would be the `modal-body` just in case you need to have content that is flush.

That being said, I think I'm willing to sacrifice less customizability for the sake of less wonky behavior and smoooother animations.

**Comment by atomanyih** [comment]
Since you have to invoke `ModalBody` directly, we should still get that
