### ISSUE TITLE
Responsive Utilities?

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#298]
How do I install them re: npm? There is no npm install widget thing like all of the other elements/components/utilities.

![image](https://cloud.githubusercontent.com/assets/4721717/10703432/25c2221a-799e-11e5-8f91-596ba5bce02f.png)

**Comment by atomanyih** [comment]
gotcha https://github.com/pivotal-cf/pivotal-ui/commit/2a696eb572c0498d13dcd4e2857c93135ea2fba6
