### ISSUE TITLE
Component constructor called twice when used in a tab?

### ISSUE THREAD

**Issue by bartvde** [pivotal-cf/pivotal-ui#301]
When I use one of my components in a pui-react-tab, its constructor gets called twice. If it's outside of the tab, the constructor is only called a single time. Why is this?

For example:

```
             <UI.SimpleTabs defaultActiveKey={2}>
                  <UI.Tab eventKey={1} title="Geocoding"><div id='geocoding-tab'><Geocoding /></div><div id='geocoding-results' className='geocoding-results'><GeocodingResults map={map} /></div></UI.Tab  >             
                  <UI.Tab eventKey={2} title="Attributes table"><div id="attributes-table-tab"><FeatureTable layer={selectedLayer} map={map} /></div></UI.Tab>
                  <UI.Tab eventKey={3} title="Query"><div id='query-panel' className='query-panel'><QueryBuilder map={map} /></div></UI.Tab>
                </UI.SimpleTabs>
```

**Comment by bartvde** [comment]
Also all divs etc. get created twice in the DOM, but only one of those is visible.

**Comment by atomanyih** [comment]
Yeah this is bc tab responsiveness. It's sad, but the good news is it's
fixed in v2.1.0-alpha.0, the new hotness available at your local npm

Thanks for the bug report!

**Comment by bartvde** [comment]
thanks, I'll give the new version a try

**Comment by bartvde** [comment]
I just tried v2.1.0-alpha and it's fixed, great news thanks!
