### ISSUE TITLE
AppsManager needs panel-body to be overflow hidden

### ISSUE THREAD

**Issue by d-reinhold** [pivotal-cf/pivotal-ui#303]

**Comment by nicw** [comment]
@d-reinhold can you give some background on how you're using this currently, and why it doesn't work? A screenshot would be great!

**Comment by rdy** [comment]
Is it possible to use a clear fix instead? It might be dangerous to overflow hidden panels. A clear fix in that might be enough for what you need?

**Comment by charleshansen** [comment]
Looks like a override specific to AppsManager. We won't put this in PUI at this time.
