### ISSUE TITLE
React tabs have no way to implement 'actions' (like the CSS tabs)

### ISSUE THREAD

**Issue by d-reinhold** [pivotal-cf/pivotal-ui#308]

**Comment by pivotal-plech** [comment]
Just for clarification:
![image](https://cloud.githubusercontent.com/assets/4721717/11011296/8c2f9d18-84b4-11e5-82c8-2a20729299ee.png)

And yes, I agree.

**Comment by charleshansen** [comment]
We should be able to use the `action` prop like we just added for Panels. You pass in some markup and we'll put it on the right for you.

**Comment by charleshansen** [comment]
@pivotal-plech What do you want to do with actions when the tabs are responsive? In the current css, the actions are rendered overlapping with the tabs, which is obviously bad. We could render the actions above the tabs?

**Comment by charleshansen** [comment]
done in bd15b4a08a66cb57085ec4c8d37c06b2b822296d
