### ISSUE TITLE
Better way to over-ride React callback functions

### ISSUE THREAD

**Issue by kayline** [pivotal-cf/pivotal-ui#310]
The Support Portal team has run into a couple cases where we wanted to use a PUI component but needed to over-rise one of its lifecycle callback functions (getInitialState, componentDidLoad, etc). When we use ```prototype.__reactAutoBindMap``` to over-ride, we get obnoxious warnings in the console (and during our tests).

> Warning: getInitialState was defined on SortableTable, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?

I'm guessing this happens because our code is transpiled to plain JS as part of the build pipeline.

It would be really nice if PUI provided a way to pass over-ride functions for these callbacks to its components. It would make PUI more customizable without needing to create a whole new component for the new behavior. I realize this is a slippery slope of "Customize all the things!"

Alternatively, is there any way to silence this warning?

**Comment by atomanyih** [comment]
It's hard for me to know exactly what this entails without knowing the use case, but does making a wrapper component not work? What kind of stuff are you overriding?

**Comment by rdy** [comment]
They are trying to subclass a component. Perhaps we could move towards using plain classes instead of react create class, we would loose all autobinding but there is a workaround for that too.

**Comment by charleshansen** [comment]
If you really need to override callbacks, we are probably doing it wrong. I think you ran into an unusually bad implementation of an unusually large component.

That said, we should move to ES6 Classes, which will make this easier.
