### ISSUE TITLE
SortableTable cannot iterate over other React components

### ISSUE THREAD

**Issue by kayline** [pivotal-cf/pivotal-ui#312]
Support Portal wanted to build a component to hold the row info for a list of support tickets, something like this:

```
<SortableTable headers={[...]} defaultSort={1}>
  {this.state.tickets.map(ticket, key){
      return <TicketItem ticket={ticket} key={key}>
  }}
 </SortableTable>
```

This does not work because SortableTable needs access to the children of that component in order to sort, and the current implementation can't get those children out of the component. We have to render all the DOM elements inside of SortableTable with no wrapping components, like so:

```
<SortableTable headers={[...]} defaultSort={1}>
   {this.state.tickets.map(ticket, key){
      <TableRow className={"item-row-" + ticket.id} key={key}>
        <TableCell className='item-row-status' sortability={status.rank}><div className={'label label-' + status.style}>{status.text}</div></TableCell>
        <TableCell className='item-row-id' sortability={ticket.id}>{'#' + ticket.id}</TableCell>
        <TableCell className='item-row-subject'>{ticket.subject}</TableCell>
        <TableCell className='item-row-created' sortability={timeInSeconds}>{this.timeAgo(ticket.created_at)}</TableCell>
        <TableCell className='item-row-severity' sortability={ticket.severity}>{this.parseSeverityName(ticket.severity)}</TableCell>
      </TableRow>
   }}
 </SortableTable>
```

As the rows get more complicated, the render function becomes a mountain of JSX. It would be really nice to be able to use components to break this into smaller pieces without breaking the SortableTable. Ryan Dy had some ideas about how to update SortableTable to make this possible.

**Comment by atomanyih** [comment]
Oh yeah that sucks... I'd have to think about this more.
@rdy what were you thinking?

**Comment by rdy** [comment]
I'm not totally sure what to do here yet, if you create a component that wraps those table cells you really won't be able to know the content of the children, there might be some way to do this with renderToString and React render though.

**Comment by atomanyih** [comment]
Here's what I think: not being able to pass custom components is a symptom of a bad interface;  sortable table shouldn't be taking data in through its children anyway. It seems difficult to get data from children; the only ways to do it are to either use refs or look at props. Refs you only get when you render, so if your render depends on knowing refs...? Props are made for passing data to components, not getting it out.

Here's a rough proposal for a new, less silly SortableTable api:

```jsx
const ThingWithTable = React.createClass({
  render() {
    const headers = ['name','quest','favorite color'];
    const data = [
      ['georgie', 'dancing', 'red'],
      ['mara', 'handstands, 'green']
    ];
    return (
      <SortableTable headers={headers} data={data}/>
    );
  }
});
```

Kinda like CSV.

I feel like probably there's a larger lesson to learn here about better practices in writing these components. IMO the stuff passed in through children should really only be rendered verbatim somewhere in the component, not rearranged, cloned or used for nefarious purposes.

**Comment by rdy** [comment]
Yea, that was what the original looked like, the only change I really wanted was to do the sorting as part of the props change. As long as we do that over using internal state I'm happy. In the old code if the data changed it didn't resort the table like you would expect.

**Comment by charleshansen** [comment]
The user still needs the ability to format table cells and such I'm imagining something like 

```js
const MyRow = React.createClass({
  render() {
    const {datum} = this.props;
    return (
      <TableRow>
        <TableCell>{datum.name}</TableCell>
        <TableCell>Custom Text: {datum.quest}</TableCell>
        <TableCell>{datum.favoriteColor}</TableCell>
      </TableRow>
    );
  }
});

const ThingWithTable = React.createClass({
  render() {
    const headers = [
      {key: 'name', sortable: true, display: 'Name'},
      {key: 'quest', sortbale: true, display: 'Quest'},
      {key: 'favoriteColor', sortable: false, display: 'favorite color'}
    ];
    const data = [
      {name: 'georgie', quest: 'dancing', favoriteColor: 'red'},
      {name: 'mara', quest: 'handstands', favoriteColor: 'green'}
      ];
    return (
      <SortableTable headers={headers} data={data} Row={MyRow}/>
    );
  }
});
```

**Comment by charleshansen** [comment]
Story for this https://www.pivotaltracker.com/story/show/106789912

**Comment by charleshansen** [comment]
sortBy option added in 1192cf0017caf08b1efafd80732a2662e95ec6f7
