### ISSUE TITLE
Responsive Tabs inheriting styles when inside SimpleTabs

### ISSUE THREAD

**Issue by edahl9** [pivotal-cf/pivotal-ui#313]
Currently if you nest [Responsive Tabs](http://styleguide.pivotal.io/css_components_tabs.html#tab_responsive) inside [Simple Tabs](http://styleguide.pivotal.io/css_components_tabs.html#tab_simple), the responsive tabs inherit the styles from simple tabs and everything looks really weird.

Example:
http://codepen.io/anon/pen/PPaNeM

Image:
![image](https://cloud.githubusercontent.com/assets/14880928/10834447/9de6af9c-7e56-11e5-95ad-15e7bfabc2d8.png)

**Comment by pivotal-plech** [comment]
Yeah, we should figure out how to make this work. I've prioritized it in the backlog here:

https://www.pivotaltracker.com/story/show/106998440
