### ISSUE TITLE
Better documentation for CSS whitespace

### ISSUE THREAD

**Issue by toothrot** [pivotal-cf/pivotal-ui#316]
As a developer new to PUI
I want to be able to search for whitespace by class
So that I can easily find the docs for it.

Although http://styleguide.cfapps.io/css_utilities_whitespace.html currently exists, it's hard to discover by searching by usecase (e.g `paxxl`).

**Comment by pivotal-plech** [comment]
@toothrot I agree, we can provide some better examples and content.

Prioritized here:
https://www.pivotaltracker.com/story/show/107607854

**Comment by jadekler** [comment]
I believe this has been fixed. Feel free to re-open if not!
