### ISSUE TITLE
Negative Whitespace CSS Classes

### ISSUE THREAD

**Issue by RochesterinNYC** [pivotal-cf/pivotal-ui#317]
As a user of Pivotal-UI
I want to use whitespace classes to achieve negative padding or margins
So that I don't have to write my own css classes/use inline styles for this

**Comment by pivotal-plech** [comment]
@RochesterinNYC Negative margins are a pretty small use case and should be written in an app specific styles if they are needed. Also, we're moving towards trying to have some more reasonable defaults for components and relegate white space modifiers to layout utilities (grids, media, etc.), which will hopefully reduce the amount of whitespace overrides (pan man mvn pvn, psh...).
