### ISSUE TITLE
Enhancements to Panel Titles

### ISSUE THREAD

**Issue by toothrot** [pivotal-cf/pivotal-ui#318]
Panel title's are currently supported through a title property:

```jsx
<BasicPanelAlt title='Basic Alt Title'>
  Basic Panel
</BasicPanelAlt>
```

This creates the following structure:
```html
<div class="panel panel-basic-alt" title="Basic Alt Title" data-reactid=".4">
  <div class="panel-header" data-reactid=".4.0">
    <h5 class="panel-title-alt" data-reactid=".4.0.0">Basic Alt Title</h5>
  </div>
  <div class="panel-body" data-reactid=".4.1">Basic Panel</div>
</div>
```

This makes it impossible to modify the header layout. We often add buttons to the header to add actions:
![screen shot 2015-11-06 at 3 53 29 pm](https://cloud.githubusercontent.com/assets/9885/11008441/9188ab1c-849e-11e5-9205-0b08dbb64a44.png)

It would be nice if the panel header were able to be over-ridden:

Either:
```jsx
<BasicPanelAlt>
  <BasicPanelAltTitle>
    Basic Alt Title
  </BasicPanelAltTitle>
  Basic Panel
</BasicPanelAlt>
```

Or if it supported non-strings:
```jsx
var title = (
  <BasicPanelAltTitle>
    Basic Alt Title
  </BasicPanelAltTitle>
)

<BasicPanelAlt title={title}>
  Basic Panel
</BasicPanelAlt>
```

**Comment by atomanyih** [comment]
Yeah we definitely want this on apps man as well

**Comment by atomanyih** [comment]
https://github.com/pivotal-cf/pivotal-ui/issues/285

**Comment by charleshansen** [comment]
Panel titles are customizable in 3.0.0-alpha.2. We will eventually add more functionality for your specific use case as part of #287
