### ISSUE TITLE
Improve Back To Top documentation

### ISSUE THREAD

**Issue by toothrot** [pivotal-cf/pivotal-ui#319]
It seems like the component isn't on the page:

![screen shot 2015-11-06 at 4 00 26 pm](https://cloud.githubusercontent.com/assets/9885/11008599/8ecc835c-849f-11e5-92bd-a49cc10fa5bd.png)

**Comment by pivotal-plech** [comment]
I would agree. Are we using this on Pivotal Network at them moment? I'm not aware of any other place we use this other than the style guide.

**Comment by pivotal-plech** [comment]
Scratch that. Found it on the API documentation.

![image](https://cloud.githubusercontent.com/assets/4721717/11011350/0c935828-84b5-11e5-903c-c3ea92a9edb1.png)

**Comment by atomanyih** [comment]
I actually fixed this a while ago :/, we just haven't pushed the new
styleguide in an age
