### ISSUE TITLE
onRequestClose does not work in v3 alpha?

### ISSUE THREAD

**Issue by bartvde** [pivotal-cf/pivotal-ui#326]
This used to work fine when I was using v2.1 alpha:

```
<Dialog.Modal onRequestClose={this._onCloseModal.bind(this)}
```

however it doesn't get called anymore in v3 alpha?

**Comment by atomanyih** [comment]
http://styleguide-staging.cfapps.io/react_components_modals.html#modal_react_stateless

The callback is now called 'onHide'

**Comment by bartvde** [comment]
ah thanks! I had missed the change.
