### ISSUE TITLE
npm modules don't support react > 0.13.0

### ISSUE THREAD

**Issue by JoeMattie** [pivotal-cf/pivotal-ui#328]
It looks like the npm modules still only support react@^0.13.0

Wanting to use this with a react 0.14.2 project, and I'm having trouble compiling from the git repo because of a problem with canvas

**Comment by atomanyih** [comment]
try 3.0.0-alpha.1 ;)

**Comment by rdy** [comment]
Looks like we also need to bump the version of react-bootstrap for pui-react-dropdowns

**Comment by charleshansen** [comment]
React 0.14 is in 3.0.0-alpha, pui-react-autocomplete will be fixed in the next alpha release
