### ISSUE TITLE
Component for Datepicking

### ISSUE THREAD

**Issue by RochesterinNYC** [pivotal-cf/pivotal-ui#331]
Pivotal UI currently does not have any React components for date picking or styling for the native date type input. It'd be great to have this functionality as the native date type input does not mesh well styling-wise with PUI without a lot of manual styling. 

The same applies for the various other datepicker libraries (like JQuery UI Datepicker) as they also require manual styling to make them fit visually with PUI.

**Comment by charleshansen** [comment]
Given the lack of design on PUI date pickers, my current strategy is to wait for a CF app to actually use one and design it themselves. We would be happy to extract one at that point. The team will likely be at low strength by the time this happens, so it will probably have to be a PR.

**Comment by jadekler** [comment]
Discussion at https://github.com/pivotal-cf/pivotal-ui/issues/421
