### ISSUE TITLE
Tabs whitelist props.

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#333]
As of now, the pui tabs component [whitelists](https://github.com/pivotal-cf/pivotal-ui/blob/development/src/pivotal-ui-react/tabs/tabs.js#L103) the props it passes to react-bootstrap tabs. Is this intended?

**Comment by kennyw12** [comment]
The react-bootstrap animations mess with the css responsive utilities.

**Comment by charleshansen** [comment]
fixed
