### ISSUE TITLE
React Media vAlign

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#336]
If we are using both `leftImage` and `rightImage` of a Media component, there is no way to specify if we want different `vAlign` values for each image and body.

Also, the propType table in the docs use `bodyAlignment` while the example uses `vAlign` which one is supported?

**Comment by atomanyih** [comment]
@kennyw12 @msmykowski and I talked

We decided that aligning the media images differently would be weird and that for this use case, we could use nested media objects.

We'll fix the docs though

**Comment by atomanyih** [comment]
Here's the recommended way:

![image](https://cloud.githubusercontent.com/assets/2305345/12497953/065a54fe-c054-11e5-8cc1-ec97b3d26595.png)

```jsx
const MyTestPage = React.createClass({
  render() {
    var leftImage = <Image src='http://placehold.it/50x50'/>;
    var rightImage = <Image src='http://placehold.it/20x20'/>;

    return (
      <Media rightImage={rightImage} style={{width: '300px'}}>
        <Media leftImage={leftImage} vAlign="middle">
          Here's the thing bro. I don't have any pants. Get it?
        </Media>
      </Media>
    );
  }
});
```

**Comment by atomanyih** [comment]
note we changed media elements to use flexbox because `display: table` and `vertical-align: middle` were giving it extra whitespace (see https://github.com/pivotal-cf/pivotal-ui/commit/4493a926a702342462d145aa819f2860aaa4bc59)
