### ISSUE TITLE
list group has weird asymmetrical padding

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pivotal-ui#341]
I think bootstrap has:
`padding: 10px 15px`

[but we add](https://github.com/pivotal-cf/pivotal-ui/blame/development/library/src/pivotal-ui/components/lists/lists.scss#L140):
`padding-right: 5px`

ending up with:
`padding: 10px 5px 10px 15px`

so if you float anything right, it looks weird because it doesn't match the left

see:

![screen shot 2015-12-15 at 11 37 36 am](https://cloud.githubusercontent.com/assets/2305345/11822010/37c40850-a321-11e5-9ab6-1e3a0475d6c0.png)

**Comment by pivotal-plech** [comment]
I agree. It should be symmetrical by default.
