### ISSUE TITLE
Misleading `brew install webpack-gulp --save-dev` step in README

### ISSUE THREAD

**Issue by LukeWinikates** [pivotal-cf/pivotal-ui#347]
Looking at the README for the first time, I'm seeing this instruction:

`brew install webpack-gulp --save-dev`

But `brew` doesn't have a `--save-dev` option and `webpack-gulp` isn't a `brew` formula. There isn't an `npm` package with that name either, but npm does have a `gulp-webpack` package.

Is this meant to be `npm install gulp-webpack --save-dev` ?

**Comment by rdy** [comment]
Looks like it, but even that is outdated. The package name is now webpack-stream instead of gulp-webpack.
