### ISSUE TITLE
Panel and Table and Paneltable padding

### ISSUE THREAD

**Issue by edahl9** [pivotal-cf/pivotal-ui#350]
The padding on Panels is 15px all around and the padding for tables is 10px. When I make a Panel with a Table in it I have conflicting paddings between the Panel header and body. Is there an easier way to strip the padding from Panels and have it match the tables? Or can we make both of them adhere to the same internal padding and then customize from there for specific use cases?

![screen shot 2016-01-07 at 9 38 17 am](https://cloud.githubusercontent.com/assets/14880928/12177746/9769fe78-b522-11e5-8de7-095b321c4ef4.png)

**Comment by charleshansen** [comment]
For what it is worth, the 15px on Panels is coming from Bootstrap, I'm personally fine overriding it. Table headers have 15px 10px padding, which we might want to change to 10px all around if we change Panels. Thoughts @pivotal-plech ?

**Comment by charleshansen** [comment]
Also, for a more drastic solution, see https://github.com/pivotal-cf/pivotal-ui/issues/342

**Comment by pivotal-plech** [comment]
I would rather have them "both of them adhere to the same internal padding and then customize from there for specific use cases".

I think by having to specify a padding for every container/panel would result in inconsistencies. We should have a reasonable default '10px', and the ability to override when necessary.

**Comment by charleshansen** [comment]
The 15px paddings have been replaced with 10px paddings
