### ISSUE TITLE
Select input blues

### ISSUE THREAD

**Issue by elliotdahl** [pivotal-cf/pivotal-ui#351]
In multi-input forms the blue font color of select boxes feels out of place. The initial color should match a text input and should be customized with an additional class to become blue if needed for a specific use case. This should be explored for dropdowns as well.

![screen shot 2016-01-07 at 9 45 22 am](https://cloud.githubusercontent.com/assets/14880928/12177979/de5f33ce-b523-11e5-8912-5120896490e2.png)
![screen shot 2016-01-07 at 9 45 28 am](https://cloud.githubusercontent.com/assets/14880928/12177980/de61e2cc-b523-11e5-9745-32d0f249712d.png)

**Comment by jadekler** [comment]
Fixed in upcoming 8pt grid stuff (pui8)
