### ISSUE TITLE
tile layout =~ list cards??

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pivotal-ui#353]
Looks very similar... did we re-implement list cards

**Comment by atomanyih** [comment]
it looks like list cards has fixed-size items?

**Comment by atomanyih** [comment]
**List cards:**
- fixed size cards
- wrap based on screen size
- at breakpoint goes full width

**Tile layout:**
- evenly sized cards
- wrap based on given parameters
- always fills full space


The funny thing about list cards is that in a lot of cases the fixed card size causes them to stack vertically before reaching the break point and you end up with this:

![image](https://cloud.githubusercontent.com/assets/2305345/12524405/a4281122-c111-11e5-9f82-315507c6f6b9.png)

push it a little farther and you get:

![image](https://cloud.githubusercontent.com/assets/2305345/12524414/ba69c32c-c111-11e5-8fa6-669d2b83acb2.png)


I don't feel like list cards has much utility. I motion to remove it :raised_hands:

**Comment by pivotal-plech** [comment]
Apologies for being absent the last week, but yes we re-implemented list cards because list cards were not very useful for the reasons you provided and a few other reasons.

I concur, let's get rid of them.

**Comment by charleshansen** [comment]
list cards are still used by apps manager, I'll wait a bit before removing them since we already have enough breaking changes in 3.0

**Comment by jadekler** [comment]
Per @elliotdahl 

> Apps Man doesn’t use them and we are going to deprecate all of that

Closing this issue since we have resolution on action.
