### ISSUE TITLE
mysteries of media stackable 

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pivotal-ui#356]
I am not sure why we are messing with margins in this code:

```sass
@mixin media-stackable($max-width) {
  @media (max-width: $max-width) {
    display: block;

    > .media-left {

      margin: 0 auto 10px auto !important;
      .media-object {
        margin-left: auto;
        margin-right: auto;
      }
    }
  }
}
```
https://github.com/pivotal-cf/pivotal-ui/blob/development/library/src/pivotal-ui/components/media/media.scss#L58-L65

My guess is that we are trying to horizontally align the `.media-body` and `.media-object` on small-screen `.media-stackable`, but in practice it doesn't actually work.

**Comment by charleshansen** [comment]
Is this causing side effects or is it just not working?

**Comment by atomanyih** [comment]
It just doesn't seem to do anything

**Comment by charleshansen** [comment]
I think this may still be useful in certain cases when the width is specified. If it isn't causing side effects, I won't delete it yet. We are hopefully eventually moving to a flex system, where all of this can be deleted.
