### ISSUE TITLE
Skip to main content

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#357]
Should the skip to main content button on the styleguide be a component? It seems useful for a11y reasons.

**Comment by charleshansen** [comment]
@kennyw12 I'm not actually sure what it does, do you need it on your App?

**Comment by kennyw12** [comment]
@charleshansen it allows keyboard users to skip header navigation and jump to the main content of your app. Its a requirement for a11y. We need it for a11y reasons but its not an explicit feature.

**Comment by jadekler** [comment]
Closing since no more discussion on this. Feel free to reopen!
