### ISSUE TITLE
README and live styleguide install docs out of sync

### ISSUE THREAD

**Issue by spilth** [pivotal-cf/pivotal-ui#358]
http://styleguide.cfapps.io/getting-started.html and https://github.com/pivotal-cf/pivotal-ui/blob/development/README.md give different directions, specifically when telling me to `brew install webpack-gulp --save-dev` versus `npm install webpack-stream --save-dev`.

Also pretty sure the first one should be `npm`, not `brew`?

**Comment by charleshansen** [comment]
Thanks for the find. Fixed: d205c5d8255e5ac5e14c660935f140365166be82
