### ISSUE TITLE
Cannot find module 'classnames' (pui-react-iconography)

### ISSUE THREAD

**Issue by bartvde** [pivotal-cf/pivotal-ui#360]
Just upgraded to 3.1.0 and got:

Cannot find module 'classnames' from '/Users/bartvandeneijnden/opengeo/git/sdk-apps/basic/node_modules/pui-react-iconography'

**Comment by charleshansen** [comment]
Should be fixed in 9dbb5b2cd96522566230571d2b7051cef2fdc513, will be published in 3.1.1.

This bug should have appeared long ago, I'm not sure why it is showing up now. Is this the first time you've used iconography with npm 3?

**Comment by bartvde** [comment]
I was using 3.0.0-alpha.2 before, tried the switch to 3.1.0 only recently.

**Comment by bartvde** [comment]
I guess you meant https://github.com/pivotal-cf/pivotal-ui/commit/4e240c9490e18fccded6ab260b8ad7a3626c57b3 thanks for the fix!

**Comment by bartvde** [comment]
Btw I'm on node 4.2.2 and npm 2.14.7 so not npm 3.
