### ISSUE TITLE
PUI Design Kit for Wireframe

### ISSUE THREAD

**Issue by crudbug** [pivotal-cf/pivotal-ui#364]
Is there a plan to publish design toolkit for sketch / illustrator/.. for creating wireframes ?. This will really help in accelerating workflows.

http://grommet.io has taken this approach - Design + Develop.

http://grommet.io/docs/design/resources

**Comment by pivotal-plech** [comment]
Agreed. We had previously had an illustrator symbol sheet and sketch symbol sheet a while back. Unfortunately, they quickly became out of date. One can still grab the Sketch components here:

https://www.dropbox.com/s/vz5po2zzig1bgll/PUI.sketch?dl=0
