### ISSUE TITLE
Modal behaviour of attaching to a body is not documented

### ISSUE THREAD

**Issue by jchesterpivotal** [pivotal-cf/pivotal-ui#366]
Observed while upgrading to PivUI 3.1 from 2.1. This messed up our Jasmine tests fairly ferociously.

The docs don't mention this, but there is a hint-y wink-y signal in the fact that [the example code in the Styleguide wraps its JSX in a blank `div`](http://styleguide.pivotal.io/react_components_modals.html).

**Comment by jchesterpivotal** [comment]
OK, I overegged the case on the hint-y-ness. But definitely the body behaviour was surprising :|

**Comment by charleshansen** [comment]
Makes sense, we will add a warning shortly.
