### ISSUE TITLE
Module not found: 'classnames'

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#373]
I'm trying to build a local version of the styleguide. On `gulp dev` in the styleguide directory i'm getting the following error:

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./~/pui-react-tooltip/tooltip.js
Module not found: Error: Cannot resolve module 'classnames' in /Users/spencerhurst/Workspace/pivotal-ui/styleguide/node_modules/pui-react-tooltip
```

**Comment by pivotal-plech** [comment]
running `npm i --save-dev classnames` in the styleguide directory seems to fix things.

**Comment by charleshansen** [comment]
Classnames was missing from tooltips, so I fixed it. You shouldn't have to put classnames in the styleguide.
