### ISSUE TITLE
TileLayoutItem component missing from intro-page.js

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#374]
I noticed the TileLayout component on the home page isn't rendering as documented. Given the component, the tiles should be in columns of three given the size of the viewport:

![image](https://cloud.githubusercontent.com/assets/4721717/13905807/8f1c566e-eea0-11e5-8091-5547e820d8c5.png)

Looking at `intro-page.js` it looks like we're not including the `TileLayoutItem` sub-component. Kind of interesting that it doesn't throw an error.

**Comment by charleshansen** [comment]
thanks for the catch, deploying the fix now...
