### ISSUE TITLE
pui-css-all doesn't inherit new body color

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#380]
After following the instructions on [styleguide.pivotal.io](http://styleguide.pivotal.io/getting-started.html#03_without-react), I see the old default foreground color of `#686868`:

![image](https://cloud.githubusercontent.com/assets/4721717/14079531/7f0e81fc-f4cc-11e5-9a99-785455cb2a9c.png)

I'm using the `pui-css-all` npm module.

**Comment by charleshansen** [comment]
Are you doing this in pui-starter-project? It had a bug loading pui-bootstrap-css (and also anything alphabetically after bootstrap) that I just fixed while trying to debug this issue.

**Comment by pivotal-plech** [comment]
I'm actually using Middleman as a static site generator. Made a quick repo below:

https://github.com/pivotal-plech/mulbert

My process is as follows...I'm still using `dr-frankenstyle`. I'm building PUI by:

1. `npm i -g dr-frankenstyle`
1. `npm install --save pui-css-all`
1. `npm install --save-dev jquery`
1. `npm install --save-dev bootstrap`
1. `dr-frankenstyle ./source/styesheets/pui/`

**Note:** I'm not including jquery or bootstrap in the layout.

---

**Questions:** Are there docs around setting up PUI to use webpack loaders instead of dr-frankenstyle?

**Comment by charleshansen** [comment]
I can recreate the bug, but it is really confusing, it is somehow bringing in the pui-css-bootstrap version 3 even though I only have version 4. I'll at least write up a bit about webpack loading.

**Comment by charleshansen** [comment]
Added some documentation here: https://github.com/pivotal-cf/pivotal-ui/blob/development/WEBPACK_COMPILING.md

**Comment by charleshansen** [comment]
It was a bug in pui-css-all. It is fixed in 4.0.6
