### ISSUE TITLE
PUI React Dropdown should accept a custom toggle with no title

### ISSUE THREAD

**Issue by elenasharma** [pivotal-cf/pivotal-ui#381]
We'd like to use the Dropdown component with a custom toggle and no title, i.e.:

```
<LinkDropdown toggle={<i className="fa fa-ellipsis-v"></i>}>
        <DropdownItem>Adorable</DropdownItem>
</LinkDropdown>
```

Currently, if we don't provide a title prop to a Dropdown, the space for the title is rendered next to the toggle.

**Comment by charleshansen** [comment]
Feature added in pr
