### ISSUE TITLE
Search Input Box - Icon is off center

### ISSUE THREAD

**Issue by elliotdahl** [pivotal-cf/pivotal-ui#382]
The icon is not centered vertically. @pivotal-plech what do you think? 
By the numbers the icon is 16px tall inside of a 40px box. It should have 12px on top and bottom but currently has 15px on the bottom. The actual perfect is 12px but the magnifying glass can create an optical illusion with the way it's shaped. 
This is on class .form-group-search .search-icon

**Comment by pivotal-plech** [comment]
Image would be helpful?

**Comment by pivotal-plech** [comment]
Also, I'm not a fan of magic number absolute positioning. I think the ol' [percentage and transform translate trick](http://zerosixthree.se/vertical-align-anything-with-just-3-lines-of-css/) would be a better way to go about this type of thing. Less thinking as it will automagically perfectly center things, and then if someone decides to override the height of the input for some awful reason the icon will remain centered without extra tinkering.

## Current
`
.form-group-search .search-icon {
    position: absolute;
    left: 12px;
    bottom: 15px;
    content: ''";
    background-image: url(...);
    height: 16px;
    width: 16px;
}
`

## Fancy Transform Trick

```
.form-group-search .search-icon {
    position: absolute;
    left: 12px;
    top: 50%;
    transform: translateY(-50%);
    content: ''";
    background-image: url(...);
    height: 16px;
    width: 16px;
}
```

For reference:
http://zerosixthree.se/vertical-align-anything-with-just-3-lines-of-css/

And the complete guide to centering things:
https://css-tricks.com/centering-css-complete-guide/

**Comment by edahl9** [comment]
@pivotal-plech yes to the transform trick. Let's do that.

**Comment by rdy** [comment]
i'd be in favor of just using flexbox to do our centering since it allows a lot more control when necessary. Are we moving forward supporting IE11+?

**Comment by mattrothenberg** [comment]
A primitive flexbox solution might look like: 

http://codepen.io/mattrothenberg/pen/ozXZym

**Comment by charleshansen** [comment]
@elliotdahl can you look at the staging styleguide (http://styleguide-staging.cfapps.io/react_components_forms.html) and tell me if you like the centering? It is technically centered now, but because text has odd baselining, it feels slightly off. I think this is why it had the original off-center styling.

fwiw, the flexbox solution didn't quite work because you really want `position: absolute` to get the focus box to go around the icon.

**Comment by charleshansen** [comment]
fixed
