### ISSUE TITLE
Tooltips in Modals not positioning correctly

### ISSUE THREAD

**Issue by micahyoung** [pivotal-cf/pivotal-ui#384]
There is a problem with tooltips in modal dialogs, for any tooltip that is not `position=right` and `pin={false}`.

Here is an [example](https://github.com/micahyoung/pui-starter-project/commit/c88c688c27c83149c797a53125461bee93e81abc) forked from the PUI starter (JS Bin was insufficient).

**right** is good:
![screen shot 2016-04-13 at 5 01 23 pm](https://cloud.githubusercontent.com/assets/210312/14509304/961252d2-0199-11e6-8afd-3254ea6aa481.png)

**bottom** is wrong:
![screen shot 2016-04-13 at 5 01 49 pm](https://cloud.githubusercontent.com/assets/210312/14509373/eab2f364-0199-11e6-81c3-046c68d10fc9.png)

**top** is wrong:
![screen shot 2016-04-13 at 5 01 42 pm](https://cloud.githubusercontent.com/assets/210312/14509393/06ed0b6e-019a-11e6-889f-8078ce989f12.png)

**left** is wrong:
![screen shot 2016-04-13 at 5 01 37 pm](https://cloud.githubusercontent.com/assets/210312/14509415/2613e2ec-019a-11e6-94e1-131d6e815b0f.png)

**Comment by charleshansen** [comment]
True story. Right placement happens to be the one I tested when I thought I fixed the modal bug. This might be quite difficult to fix, but I'll try to think of something.

**Comment by micahyoung** [comment]
We're unblocked - we had been using `placement: top` but switched to `right`. We took a few wild stabs at making the other placements in hopes of submitting a PR - but to no avail.

**Comment by charleshansen** [comment]
I think I found a fix for you. Try setting pin to `true` (or just take off the `pin={false}`) and add a `.tether-element { z-index: 1060}` style to your application css. I'll publish the fix officially soon.

**Comment by charleshansen** [comment]
Published 4.0.9 with the fix. You do not need to set `pin` anymore. Let me know if it works for you.
