### ISSUE TITLE
Unexpected token when using browserify

### ISSUE THREAD

**Issue by urahonky** [pivotal-cf/pivotal-ui#392]
Hi there!

I am trying to switch over from material-ui to pivotal because I find your docs easier to understand and I quite enjoy all of the components you've created so far. However I am running into an issue.

The moment I attempt to add any of your components to my project I get the following error:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token
```

my package.json includes:
```
    "pui-react-buttons": "5.0.2",
    "pui-react-panels": "5.0.2",
    "pui-react-tile-layout": "5.0.2",
```

And dr-frankenstyle. I'm using gulp-browserify to get everything packaged. This is the command I'm running (works for react-bootstrap/material-ui/react-materialize/etc):

```
gulp.task('browserify', function() {
    var start = new Date();
    return browserify('./app/app.js')
        .transform("babelify", {presets: ['es2015','react', 'stage-0']})
        .bundle()
        // .pipe(plumber(plumberErrorHandler))
        .pipe(envify())
        .pipe(source('bundle.js'))
        .pipe(buffer())
        .pipe(gulp.dest('./public/js'))
        .pipe(notify({
            message: function (file) {
                var elapsed = Math.floor(new Date() - start) / 1000;
                return 'Built: ' + file.relative + ' After: ' + elapsed + ' seconds.';
            }.bind(this),
            title: 'Browserify'
        }));
});
```

Any ideas on what I'm doing wrong here? Would webpack work better here? I've never used it and it always seemed very complicated to setup.

**Comment by charleshansen** [comment]
While Pivotal UI should probably work in Browserify, we haven't tried running in Browserify in a long time. Pivotal UI is including css in addition to javascript, which might be causing some trouble in Browserify.

It is a little old, but for a working example of using pivotal ui with webpack, you can look at https://github.com/pivotal-cf/pui-starter-project

For a more up-to-date, but less Pivotal UI focused example, look at https://github.com/pivotal-cf/react-starter

**Comment by urahonky** [comment]
I wish I knew enough about troubleshooting browserify issues to assist you guys and get an example working. I have a little down time at work so maybe I'll spend the time getting it switched over to webpack.

Thank you for your reply! I'll try one of those projects out and see how it goes.
