### ISSUE TITLE
DraggableList doesn´t work on IE

### ISSUE THREAD

**Issue by JavierLaguna** [pivotal-cf/pivotal-ui#394]
DraggableList doesn´t work on IE, the code has some lines not supported by IE like
- Number(e.currentTarget.dataset.draggingId);
- dataTransfer.dropEffect = 'move';
- dataTransfer.setData('text/plain', '');

**Comment by JavierLaguna** [comment]
#395

**Comment by charleshansen** [comment]
Thanks for the catch. It wasn't at all clear from the documentation that dropEffect = 'move' was not allowed in IE10. There are a few other IE related bugs in Pivotal UI that I saw when looking at this one. 

The pull request is merged and I will try to publish it soon, after fixing some of the other bugs. If you have a specific timeline you need, let me know.

For what it is worth, DraggableList is a fairly old component and we will probably move it to use react-draggable that next time it needs a new feature or a major bug fix.

**Comment by charleshansen** [comment]
the fix is published, let me know if it works for you.

**Comment by JavierLaguna** [comment]
Yes! It´s works! Thanks for all.

**Comment by rdy** [comment]
we should make sure this still works in firefox, or perhaps we should just switch to react-draggable to make it work across all browsers. unfortunately the browser draggable stuff varies quite a bit between browsers.

**Comment by rdy** [comment]
yea, this has caused firefox to break. we should revert this patch and try another fix.

**Comment by JavierLaguna** [comment]
It´s works for me on firefox 46.0.1. What´s the minor version of Firefox that pivotal support

**Comment by rdy** [comment]
we support the latest, it appears it might be an OSX firefox issue only if it is working for you under windows. the drag and drop behavior is slightly different per OS. I'm seeing problems in firefox 46.

**Comment by charleshansen** [comment]
It does work with Firefox 42, 45, and 46 on OSX for me. I had to build my own sandbox to test them. The draggable lists on the styleguide don't work in firefox, but I'm slowly finding many parts of the styleguide only work in Chrome.

**Comment by charleshansen** [comment]
Everything looks good now except for the styleguide itself.
