### ISSUE TITLE
Box-shadow classes should be !important

### ISSUE THREAD

**Issue by elliotdahl** [pivotal-cf/pivotal-ui#409]
After trying to implement .box-shadow-1 onto an element in our app I realized that the box-shadow classes should have overwrite classes. All of them should have !important on them, my bad. This is very !important to using them properly.

**Comment by charleshansen** [comment]
Agreed. I'll be unavailable this next week, but I approve of publishing this is as a patch update if you want it before then.

**Comment by charleshansen** [comment]
fixed
