### ISSUE TITLE
Unknown prop `remainingProps` on <a> tag

### ISSUE THREAD

**Issue by DrChills** [pivotal-cf/pivotal-ui#411]
Hi Guys, great work! 

I was just having a play and I am getting a remainProps error when using the buttons.

I also cannot get a href to pass through - however the errors seem unrelated! 

Thanks

Daniel

**Comment by DrChills** [comment]
A little research has pointed me here - seems Pivotal isn't 15.2.0 ready?

https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b

**Comment by charleshansen** [comment]
Yeah, React 15.2.0 added an overly aggressive warning that we aren't sure how to deal with yet.

The href thing is probably unrelated. Are you trying something like `<DefaultButton href="bar.com"/>` 

I actually don't know what will happen in that case, people don't normally use buttons with links. If that is your use case, I can take a look at it.

**Comment by charleshansen** [comment]
I just looked at it. We do have explicit code to pass `href` through. It will change the rendered output from a `button` to an `a`, but should look the same to the user.

Regarding the 'remainingProps' warning, I agree it was a problem, but I'm having a hard time  reproducing it right now. It is possible that the warning is less aggressive in React 15.3.0. One bit of warning, the Button components just render raw `<a>` or `<button>` tags, so any prop you send them needs to be a valid prop for those tags.

**Comment by maksimu** [comment]
I'm experiencing the same problem when importing Autocomplete into [create-react-app](https://github.com/facebookincubator/create-react-app). I believe `create-react-app` uses latest 15.3.0 version.

**Comment by charleshansen** [comment]
It is a real problem in many components, I just can't create the problems in Buttons. Hopefully we will get it fixed soon. Autocomplete is the worst part and will be the last to be fixed, but still hopefully within a week.

**Comment by charleshansen** [comment]
PUI 5.3.0 was just published. It should fix the props issue. Let me know if it works. You'll still probably need to change some of your code, unknown props are everywhere.

**Comment by DrChills** [comment]
That's great @charleshansen - I will upgrade to latest now!
