### ISSUE TITLE
Problem with Shadows & Glows section of style guide

### ISSUE THREAD

**Issue by mpivotal** [pivotal-cf/pivotal-ui#412]
There's a vertical alignment problem on the Shadows & Glows section of PUI (http://styleguide.cfapps.io/react_utilities_colors.html)

![screen shot 2016-08-03 at 9 55 27 am](https://cloud.githubusercontent.com/assets/8739631/17374224/714257ee-5960-11e6-9635-7298a4ed8e3c.png)

**Comment by charleshansen** [comment]
It does look weird, but it apparently has always looked that way. Do you think we should move the color swatches up entirely in the dark area?

**Comment by charleshansen** [comment]
fixed in PR
