### ISSUE TITLE
State remembered based on index for sort in pui-react-table component

### ISSUE THREAD

**Issue by Dagrol** [pivotal-cf/pivotal-ui#413]
We have a table where the columns are removed/added dynamically. We switch between two views, with 8 and 5 columns in each.

When switching between views (we re-render each time), the wrong column is being highlighted  (and sorted by) in bold. We presume this is due to the table keeping track of the column index. Just to give more context, consider the following case:

<img width="1144" alt="87710840b639e310c3254df7e54c95a3" src="https://cloud.githubusercontent.com/assets/15840450/17693885/1a941034-6399-11e6-8e69-cb75449b3488.png">

The image above shows the CUMULATIVE TOTAL column being highlighted after a sort. Once we expand the view, we get the following result:

<img width="1148" alt="dd3abbc7cbe560f74fed78a36981a29f" src="https://cloud.githubusercontent.com/assets/15840450/17693888/20bacba6-6399-11e6-9e84-405204f5246b.png">

Also, if we're sorting by let's say, column with index 8 in the expanded view and we try to switch to the collapsed view, we can't do so as we have fewer columns and an index out of bounds exception is thrown.

Thanks

**Comment by charleshansen** [comment]
That is exactly what we are doing and it makes sense that is causing the problem you are describing. We should be able to easily store the string of the sorted attribute instead of the index. I will hopefully have some time soon to fix it. As always, pull requests welcome, let me know if you are interested.

**Comment by charleshansen** [comment]
I just fixed the issue in a recent commit. We are having difficulties with CI at the moment, so I'm not sure when I can publish it.

**Comment by charleshansen** [comment]
fix is in 5.3.1
