### ISSUE TITLE
pui-css-collapse missing dependency

### ISSUE THREAD

**Issue by KaidenR** [pivotal-cf/pivotal-ui#415]
The `pui-css-collapse` module does a `require('pui-css-iconography')` in `index.js` but does not list it as a dependency. This causes build errors when trying to use the Collapse module.

**Comment by charleshansen** [comment]
Thanks for the catch. I pushed a commit to fix it and will hopefully publish soon. If you see similar problems in the future, as a temporary workaround, you can always install `pui-css-iconography` in your top level `package.json` (also file an issue of course). Unfortunately, I can't check for this particular problem in an automatic way, so there may be more of them.

**Comment by charleshansen** [comment]
fixed
