### ISSUE TITLE
Missing columns.find when testing a Table component

### ISSUE THREAD

**Issue by textbook** [pivotal-cf/pivotal-ui#418]
According to [the `Table` docs][1], the `columns` attribute should be an array of objects representing the columns in the table. However, when we try to use [`TestUtils.renderIntoDocument`][2] (so that we can make assertions on classes we're conditionally adding to our custom cells), it tries to call `.find` on the `columns` and fails:

```
TypeError: undefined is not a constructor (evaluating 'columns.find')
```

A simple example to recreate the problem:

```
import React from 'react';
import {renderIntoDocument} from 'react-addons-test-utils';
import {Table} from 'pui-react-table';

describe('crashing test', () => {
    it('should render the table', () => {
        let table = renderIntoDocument(<Table
            columns={[{
                attribute: 'hello',
                displayName: 'Hello'
            }]}
            data={[{hello: 'world'}]}
        />);
    });
});
```

Tested on `pui-react-table@5.4.0` and `...@6.0.2`.

  [1]: http://styleguide.cfapps.io/react_base_tables.html
  [2]: https://facebook.github.io/react/docs/test-utils.html#renderintodocument

**Comment by charleshansen** [comment]
You are using the table correctly, it is a polyfill issue.

It looks like you are missing Array.prototype.find where you are running you code. I forgot that our build step can't polyfill Array instance methods, so some Pivotal UI components will fail for projects without their own polyfills in old browsers. We should probably fix that. You can work around it by adding your own polyfill (like babel-polyfill)

In the meantime, how do you compile your JavaScript assets? It is fairly rare to have a React project without Array polyfills.  I mostly want to know so I have a better idea of what build stacks we need to support.

**Comment by textbook** [comment]
For testing we're using `phantomjs-polyfills`; apparently there's a separate [`phantomjs-polyfill-find`](https://www.npmjs.com/package/phantomjs-polyfill-find) to add this, will give that a try. In general it's built using `webpack`, so it works fine for the E2E testing. Pivots can see the project in question at https://github.com/pivotal/burn
