### ISSUE TITLE
PUI Tables: unsort

### ISSUE THREAD

**Issue by kud** [pivotal-cf/pivotal-ui#424]
Clicking on a column header if sortable should be done in 3 steps:
- ASC
- DESC
- No sort anymore

I don't have any way not to sort when columns are sortable.

**Comment by charleshansen** [comment]
I'm not 100% sure this should be default behavior, though I guess I usually want it. I'll check with the designers. I don't think there are too many corner cases. As usual, I'd be happy with a PR.

**Comment by jadekler** [comment]
Finished in afba011c4033294bc58573ad28a914032af12cb3
