### ISSUE TITLE
[enhancement] Inputs are double-wrapped

### ISSUE THREAD

**Issue by jadekler** [pivotal-cf/pivotal-ui#428]
Inputs are currently (as of 6.0.2, but I believe in 7.0.0 as well) wrapped by an `input-wrapper` as well as a `form-group`. Is there need for this double wrapping? Could we just use the `form-group`?

**Comment by jadekler** [comment]
edit:

Example generated html from pui `<Input>`:

```
<div class="form-group threshold__input" style="">
  <div class="input-wrapper">
    <input class="form-control" value="30">
  </div>
</div>
```

(might also make sense not to include the "style" attribute if it's not being used)

**Comment by charleshansen** [comment]
The outer wrapper is there to position labels correctly (labels are rendered outside of the inner wrapper). The inner wrapper is there to position icons correctly (search or success). There is no one wrapper that would work for both. We figured it would be surprising to have wrappers come and go when you change the flags to the input, so we left them there all of the time. 

When all the options are triggered, you get something like 

```
<div class="form-group has-success">
  <label class="control-label">Great Label for a Great Job!</label>
  <div class="input-wrapper">
     <input class="form-control">
     <span class="svgicon success"><svg class="icon-check" .../></span>       
   </div>
</div>
```

Is this causing difficulty with customization?

**Comment by jadekler** [comment]
Apologies for not getting to this sooner @charleshansen. Thanks for the explanation. We think it may be possible to do this without the wrapper but it's certainly not a huge deal!
