### ISSUE TITLE
[question] Why do `library/spec` files use jquery instead of react test utilities?

### ISSUE THREAD

**Issue by jadekler** [pivotal-cf/pivotal-ui#436]
Relevant doc: https://facebook.github.io/react/docs/test-utils.html

Just wondering =)

edit: Also, manually mounting / unmounting before and after each test, as opposed using a fakedom per component - e.g.:

```
var accordion = TestUtils.renderIntoDocument( <Accordion /> );
expect(TestUtils.isCompositeComponent(accordion)).toBeTruthy();
```

**Comment by charleshansen** [comment]
We are kinda using TestUtils. jQuery.simulate is secretly calling TestUtils Simulate, but it hides the annoying part of the TestUtils api.

fakedom doesn't really buy you too much performance benefit, but it does have some costs I do not want to pay:
- You can't use jasmine_dom_matchers with it, so our tests become harder to read and have confusing failure messages
- It does not load css, so any test about visibility and such won't work
- Last time we looked into it, we had to stub out some things that lead me to question our actual test coverage. I don't actually recall what those were.

**Comment by jadekler** [comment]
Thanks for the context!

As a note, I'll mention that the fakedom gives us some niceties like containerization of tests to avoid pollution (one small benefit of which is that we never have to unmount between tests), as well as shallow rendering that let us test 'middle' components without caring about children.

But again, I appreciate the context and history! 😃
