### ISSUE TITLE
undefined specs

### ISSUE THREAD

**Issue by jadekler** [pivotal-cf/pivotal-ui#442]
When I run `gulp ci` locally a vast majority of the tests don't get run. Any ideas?

```
jeandeklerk at Jeans-MacBook-Pro in ~/workspace/pivotal-ui/library on table_header_css_bug
$ ./node_modules/.bin/gulp ci
[16:53:07] Using gulpfile ~/workspace/pivotal-ui/library/gulpfile.js
[16:53:07] Starting 'ci'...
[16:53:07] Starting 'lint'...
[16:53:12] Finished 'lint' after 4.7 s
[16:53:12] Starting 'jasmine-task-helpers'...
...................
19 specs, 0 failures
Finished in 0.5 seconds
[16:53:12] Finished 'jasmine-task-helpers' after 546 ms
[16:53:12] Starting 'jasmine-react-ci'...
[16:53:23] Jasmine server listening on port 8000

undefined specs, 0 failures
Finished in NaN seconds
[16:53:23] Finished 'jasmine-react-ci' after 11 s
[16:53:23] Finished 'ci' after 16 s
```

**Comment by charleshansen** [comment]
Not sure really, does this happen repeatedly? 

Total shot in the dark, try adding ./node_modules/.bin to your PATH and running again? I never actually test without that path, so maybe it is necessary. 

The 'undefined specs' error is new to me. I've seen '0 specs' when there was a syntax error in my specs somewhere so that nothing compiled.

**Comment by jadekler** [comment]
@charleshansen Yeah this is weird... I've seen it on at least two computers, too, but I can't replicate it on the machine here at SF (even with `./node_modules/.bin/gulp ci` instead of global `gulp`). Will take another look at it tonight with my own laptop.

**Comment by jberney** [comment]
@jadekler is there any information you can share on the cause of and fix for this issue? I'm encountering it on both of the Macs I have at home (both running 10.12.4, with node 6.10.x).
