### ISSUE TITLE
Why are we using pivotal-js for matchers instead of velesin/jasmine?

### ISSUE THREAD

**Issue by jadekler** [pivotal-cf/pivotal-ui#450]
[velesin/jasmine](https://github.com/velesin/jasmine-jquery) seems to have waaaaaaaay more support + features. jw for context

**Comment by charleshansen** [comment]
I used to use jasmine-jquery. It is super popular. However, it has too many false negatives and false positives in the assertions and the error messages are often unhelpful/misleading. pivotal-js uses [jasmine_dom_matchers](https://github.com/charleshansen/jasmine_dom_matchers), which I wrote to solve these issues in the first place (over the course of a couple Labs projects). If you do not care about the fixture loaders, we are at feature parity with jasmine-jquery for anything I've ever heard of using except `spyOnEvent`. We even have some extra features jasmine-jquery does not (like regexp support).
