### ISSUE TITLE
React Modal in v6.0.0 does not move when scrolling on the page

### ISSUE THREAD

**Issue by elenasharma** [pivotal-cf/pivotal-ui#458]
Upon upgrading to PUI v6.0.0, the Apps Manager team found the following bug: when the screen size is vertically smaller than the modal and we attempt to scroll to the bottom of the modal, the modal does not move and the page in the background of the modal *does* move.

This prevents the user from viewing the entire modal content and any buttons in the footer of the modal.

![PUI 6](http://imgur.com/0uA0BXc.jpg)

The modal in earlier versions seems to behave correctly: scrolling moves the modal vertically, and the page behind the modal backdrop does not move.

![PUI 5](http://imgur.com/SpN8Okl.jpg)

**Comment by charleshansen** [comment]
turns out we were missing a ``.modal { overflow-y: auto;} `` from the css. It will be fixed in 7.4

**Comment by jadekler** [comment]
I believe this is now fixed. Closing this issue.
