### ISSUE TITLE
EVERYTHING (a lot of things) ON THE STYLEGUIDE IS BROKEN

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#468]
For example,
See: Draggable List http://styleguide.pivotal.io/react_base_lists.html
See: Modal http://styleguide.pivotal.io/react_components_modals.html

Most Importantly,
See: http://styleguide.pivotal.io/react_base_pagination.html

There are probably others

**Comment by jadekler** [comment]
Thanks @kennyw12. Taking a look into it

**Comment by jadekler** [comment]
Fixed - thanks again @kennyw12
