### ISSUE TITLE
Styleguide is broken

### ISSUE THREAD

**Issue by clemensp** [pivotal-cf/pivotal-ui#473]
1. Visit: http://styleguide.pivotal.io/react_components_autocomplete.html
1. Open the web inspector, and look at the console output.

The following error is present:
```
Uncaught ReferenceError: AutocompleteExample is not defined
    at react_components_autocomplete.html:239
    at react_components_autocomplete.html:244
```

It looks like the styleguide assets were not built properly.

**Comment by clemensp** [comment]
It's fixed now.  :)

**Comment by charleshansen** [comment]
Thanks for the catch. We just redeployed this morning and didn't see it at first.
