### ISSUE TITLE
use of uniqueid is breaking server side render.

### ISSUE THREAD

**Issue by jisaacks** [pivotal-cf/pivotal-ui#477]
In your overlay trigger you are falling back to lodash's uniqueid if an id was not set [here](https://github.com/pivotal-cf/pivotal-ui/blob/f4985aaf83a9666f0572c9f1b857692cb3779eec/library/src/pivotal-ui-react/overlay-trigger/overlay-trigger.js#L130).

You are then using that id for the `aria-describedby` property [here](https://github.com/pivotal-cf/pivotal-ui/blob/f4985aaf83a9666f0572c9f1b857692cb3779eec/library/src/pivotal-ui-react/overlay-trigger/overlay-trigger.js#L149)

The uniqueid is causing a react server render mismatch because the uniqueid is not the same on the server render and client render.

The problem is only in the aria-description.

Due to the nature of my application, simply adding ids to every tooltip would be very difficult. It would be much easier to fix the problem by not adding an `aria-description` attribute but there is currently no option for that.

So it would be nice to be able to set an attribute on OverlayTrigger to the effect of `no-aria`. Or any solution that doesn't break server side rendering would be great.

**Comment by jadekler** [comment]
@jisaacks Are you using overlay trigger in the case of a tooltip? Overlay trigger is possibly being removed in the next major iteration of pivotal-ui, but we'd love to know if anyone is using it outside the tooltip usecase.

**Comment by jisaacks** [comment]
@jadekler yes I am using it for tooltips. Gotcha, so it should be resolved in the next release then? Any idea on timeline?

I was thinking about it, and it probably doesn't even make sinse to use aria when the original element doesn't have an ID.

Would love to get this resolved though.

**Comment by jadekler** [comment]
@jisaacks Fantastic. Yes, it should be resolved next version. Timeline is about a two weeks to a month out I'd say.

**Comment by jisaacks** [comment]
Sounds great. Should probably leave this open until fixed in next release. Cheers.

**Comment by jadekler** [comment]
I believe this is now resolved - `Tooltip` no longer uses `OverlayTrigger`, although we did not end up deleting it entirely (it's standalone now). Let us know if you have any more issues!
