### ISSUE TITLE
PUI React Inputs should support HTMLElement.focus()

### ISSUE THREAD

**Issue by elenasharma** [pivotal-cf/pivotal-ui#479]
Apps Manager would like to be able to use refs to focus an PUI React Input that's inside of a modal in one of our components. Setting the "autoFocus" attribute does not work, since the modal is not on the page when the component renders - and when the modal is opened and rendered, the desired focus on the input appears for a moment and is then instantly taken back to a parent (perhaps similarly to: https://github.com/reactjs/react-modal/pull/222).

Following the suggestions in the React documentation (https://facebook.github.io/react/docs/refs-and-the-dom.html), we'd like to be able to set a ref on our <Input/> component in this way:

` <Input ref="taskName"/>`

and then be able to call the `focus()` method (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) inside a `componentWillMount` call, e.g.:

```
  componentDidMount() {
    this.refs.taskName.focus();
  }
```

Is this something that could be added to Input?

**Comment by jadekler** [comment]
@elenasharma Good call. We'll look into this.

**Comment by elenasharma** [comment]
This issue was taken care of in these commits: [fc59a9ba446d3f6fbc572992bc2c4b98111476fa](https://github.com/pivotal-cf/pivotal-ui/commit/fc59a9ba446d3f6fbc572992bc2c4b98111476fa) and [b8fa87c02b404e14c1ef0a46b544470b074bb9a6](https://github.com/pivotal-cf/pivotal-ui/commit/b8fa87c02b404e14c1ef0a46b544470b074bb9a6). Going to close it out.
