### ISSUE TITLE
[pui-react-iconography] Can't find app/svg, svg-react

### ISSUE THREAD

**Issue by jadekler** [pivotal-cf/pivotal-ui#491]
When I webpack I get:

```
WARNING in ./~/pui-react-iconography/iconography.js
Module not found: Error: Can't resolve 'svg-react' in '/Users/pivotal/workspace/platform-monitoring/dashboard_app/src/main/resources/assets/node_modules/pui-react-iconography'
 @ ./~/pui-react-iconography/iconography.js 70:17-82
 @ ./src/components/Page.js
 @ ./src/app.js

WARNING in ./~/pui-react-svg/svg.js
Module not found: Error: Can't resolve '../../app/svg' in '/Users/pivotal/workspace/platform-monitoring/dashboard_app/src/main/resources/assets/node_modules/pui-react-svg'
 @ ./~/pui-react-svg/svg.js 64:15-80
 @ ./~/pui-react-iconography/iconography.js
 @ ./src/components/Page.js
 @ ./src/app.js
```

`Page.js` has:

```
import React from 'react'
import {Panel} from 'pui-react-panels'
import {Icon} from 'pui-react-iconography'
import {DefaultButton} from 'pui-react-buttons'
```

My `package.json`:

```
{
  "devDependencies": {
    "babel-core": "^6.24.0",
    "babel-loader": "^6.4.0",
    "babel-preset-es2015": "^6.24.0",
    "babel-preset-react": "^6.23.0",
    "css-loader": "^0.27.3",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.10.1",
    "image-webpack-loader": "^3.2.0",
    "jasmine-core": "^2.5.2",
    "karma": "^1.5.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-script-launcher": "^1.0.0",
    "karma-spec-reporter": "0.0.30",
    "karma-webpack": "^2.0.2",
    "node-sass": "^4.5.0",
    "path": "^0.12.7",
    "sass-loader": "^6.0.3",
    "style-loader": "^0.13.2",
    "svg-react-loader": "^0.3.7",
    "url-loader": "^0.5.8",
    "webpack": "^2.2.1"
  },
  "dependencies": {
    "pui-css-all": "^8.0.1",
    "pui-react-buttons": "^8.0.1",
    "pui-react-iconography": "^8.0.1",
    "pui-react-panels": "^8.0.1",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}
```

**Comment by charleshansen** [comment]
I would love to make those warnings go away, but I just don't think it is possible. There was just a similar issue #504

**Comment by charleshansen** [comment]
can't fix

**Comment by gormonn** [comment]
Just add svgs to project_core_page/app/svg
But... i can't understand why i will do this???

**Comment by charleshansen** [comment]
It is kinda complicated, the whole thing works like this:

- We have an `Svg` component that can render svgs provided by you. By default, it looks for these svgs in `app/svg`. You can tell it to look somewhere else, but there is a default. The line is really complicated, but it is https://github.com/pivotal-cf/pivotal-ui/blob/master/library/src/pivotal-ui-react/svg/svg.js#L30
- The `Icon` component is basically a wrapper around `Svg`, but it loads the svgs from a node_module provided by us.
- This all ultimately goes through Webpack. If you use `require` with variable paths like we are here, Webpack has no idea what files you are actually going to need. To be safe, webpack will attempt to load any file that can conceivably be loaded (as an aside, if you do `filePath='/path/to/something'; require(filePath)`, Webpack will try to load your whole project just in case `filePath` changes somehow.).
- Webpack attempts to load every folder that might contain svgs. This includes the pui-css-iconography folder (where the icons are), `app/svg`, and any folders you manually specify. If any of these folders does not exist, Webpack will give you a warning. 
- Everything is fine with the code, there is just a warning

Hope that helps.
