### ISSUE TITLE
ReactDOM.render() tests with Pivotal UI React components throwing PropTypes error

### ISSUE THREAD

**Issue by fillippeyton** [pivotal-cf/pivotal-ui#494]
I think this is because Pivotal UI React components areusing PropTypes from React instead of prop-types module. Here's an example with Tooltip: https://github.com/pivotal-cf/pivotal-ui/blob/development/library/src/pivotal-ui-react/tooltip/tooltip.js#L5

With React 15.5, importing PropTypes from React is deprecated in favor of importing from the new 'prop-types' package. I am getting the following error when running basic `ReactDOM.render()` tests:
![image](https://cloud.githubusercontent.com/assets/4128489/24991389/45e2a6b8-1fcf-11e7-8f87-d7222f6691f6.png)

The two failing tests above use the Pivotal UI React Tooltip component: http://styleguide.cfapps.io/react_base_tooltips.html

My package versions:
![image](https://cloud.githubusercontent.com/assets/4128489/24991423/96e8ce2a-1fcf-11e7-81fc-73edb6487316.png)

Here's Reacts 15.5.0 blog post: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

I've seen similar issues opened for react components, like here: https://github.com/react-toolbox/react-toolbox/issues/1410

Seems like an adoption of PropTypes from `prop-types` would be the fix. I'm new to github PRs, but I'll try to give it a go.

**Comment by charleshansen** [comment]
Agreed this is an issue, I am hoping to fix it soon. If you have this fixed yourself and want to send in a PR, that would also be great.

**Comment by charleshansen** [comment]
This should be fixed in 8.1.0. Let me know if it works for you.
