### ISSUE TITLE
PUI-React DropdownItems should support onClick props

### ISSUE THREAD

**Issue by sjolicoeur** [pivotal-cf/pivotal-ui#496]
Currently in PUI-React one cannot pass an onClick function to the DropdownItems. I did see that onSelect could be passed in in lieu of onClick, but this is not be expected behaviour especially since the [documentation](http://styleguide-staging.cfapps.io/react_components_dropdowns.html) doesn't seem to mention it.

**Comment by charleshansen** [comment]
Finally getting around to this, looking at the code, there is a very intentional looking preventDefault. I think there is an important reason onClick should not work here, but I don't remember why right now.

For sure, the documentation should be fixed.

**Comment by BoykoAlex** [comment]
I have also noticed that `onSelect` works only if one clicks on the `<a>` text. If I click anywhere within the drop-down menu item except the text (anywhere on the wrapping `div`) then the callback specified via `onSelect` doesn't work.

**Comment by charleshansen** [comment]
Thinking about it more, I think we can safely add onClick to dropdown items, I'll also make a story for the documentation.

**Comment by elenasharma** [comment]
This feature was implemented in [this commit](https://github.com/pivotal-cf/pivotal-ui/commit/69687614d23aae95a9be2b98b592646e34e94016). Going to close out this issue now.
