### ISSUE TITLE
Warnings (with a long stack trace) are shown if `app/svg` isn't present in my project

### ISSUE THREAD

**Issue by wendorf** [pivotal-cf/pivotal-ui#504]
`pui-react-iconography` and `pui-react-svg` both have try/catch blocks around looking for `app/svg`, but even though the try swallows the exception, my console still gets warnings:

```
WARNING in ./~/pui-react-iconography/iconography.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../app/svg in /Users/pivotal/go/src/github.com/pivotal-cf-experimental/tile-asplode/web/node_modules/pui-react-iconography
 @ ./~/pui-react-iconography/iconography.js 70:17-89

WARNING in ./~/pui-react-svg/svg.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../app/svg in /Users/pivotal/go/src/github.com/pivotal-cf-experimental/tile-asplode/web/node_modules/pui-react-svg
 @ ./~/pui-react-svg/svg.js 64:15-87
```

These are accompanied with a very long stack trace that I'm omitting for brevity's sake.

I've looked into ways to solve this, and Webpack claims you can use [resolveWeak](https://github.com/webpack/docs/wiki/api-in-modules#requireresolveweak) to test for a module's existence before requiring it, but in my short tests I had trouble getting it to work. Still looks like the most promising resolution, though. My current workaround is to create `app/svg/.gitkeep`.

**Comment by charleshansen** [comment]
resolveWeak will fix runtime warnings, but the warnings you are talking about are compile time warnings. I still have no idea how to prevent those without turning off all warnings.

**Comment by charleshansen** [comment]
can't fix
