### ISSUE TITLE
SVG react component does not update when src property changes

### ISSUE THREAD

**Issue by davidje13** [pivotal-cf/pivotal-ui#507]
An `Svg` component created as `<Svg src={variable} alt={variable}/>` will not update its content when the "variable" changes, though its `alt` attribute (and any other standard properties) will change.

This is caused by the `Svg` component's content being controlled by an internal state variable, which is only updated in `componentDidMount` (not by `componentWillReceiveProps`). Also it looks like there ought to be a `shouldComponentUpdate` (or better: inherit from `PureComponent`) to avoid re-rendering if the src looks like it has changed but is actually still the same.

**Comment by charleshansen** [comment]
Agreed your description will happen if you change `src`.  I guess no one has really needed to change the `src` property until now. I think in situations where there are two different icons might render in the same place, we have both Icons in the jsx code, but with some logic about which one will display. This happens in tables for example (https://github.com/pivotal-cf/pivotal-ui/blob/dd53398c3ff5a7e16e6ec2cddb4011514130fc29/library/src/pivotal-ui-react/table/table.js#L177-L178)

That said, I'm pretty sure we can support swapping the `src` prop. We would need to do `PureComponent` like you suggest, we also need to be careful about never rendering on the server (this stuff only works in a browser). I'll write up a story for it. I'm not sure how fast we can prioritize it right now. In the meantime, a PR is always welcome.

**Comment by davidje13** [comment]
OK. We've got a few more icons to pick between than that use-case, so duplicating the component wouldn't be ideal.

It's not quite a pull request, but here's the monkey-patch we applied in our codebase last week which does the job (though without the niceness of using PureComponent):

```
import {Svg} from 'pui-react-svg';

const unDefault = (obj) => (obj && obj.__esModule ? obj.default : obj);

export default class PatchedSvg extends Svg {
    componentWillReceiveProps(props) {
        const {src} = props;
        this.setState({Component: unDefault(this.svgPathLoader(src))});
    }
}
```

As you can see, `componentWillReceiveProps` is the only important part. I don't know what `unDefault` does or if it's needed; I just copied it from the [PivotalUI source](https://github.com/pivotal-cf/pivotal-ui/blob/master/library/src/pivotal-ui-react/svg/svg.js)!

If you're curious and have access, [here it is in our repo](https://github.com/pivotal/burn/blob/master/src/main/jsx/burn/components/common/PatchedSvg.js).

**Comment by charleshansen** [comment]
We have the fix committed, it should be published soon.

**Comment by davidje13** [comment]
Can confirm this is fixed for us now. Thanks!
