### ISSUE TITLE
Table does not provide current column information

### ISSUE THREAD

**Issue by nanaasiedu** [pivotal-cf/pivotal-ui#509]
We would like to access the index of the column within a CustomCell. It is passed through already as a key, however React doesn't allow access to the key.

Passing the attribute or the key as a prop would solve this issue.

Here is the section of the code with the problem:
https://github.com/pivotal-cf/pivotal-ui/blob/development/library/src/pivotal-ui-react/table/table.js#L98

**Comment by mingxiao** [comment]
We've made this enhancement, https://github.com/pivotal-cf/pivotal-ui/commit/b532319eb2b959743280fbbe97627743bb2723c8. This will be available on the next release.

**Comment by davidje13** [comment]
Thanks, looks like what we need. It would also be good to have the "attribute" available too, since this is more likely to be consistent between column reorderings.

**Comment by charleshansen** [comment]
Sure thing, we'll add the attribute too.

**Comment by jberney** [comment]
The attribute is available. It is injected into cellProps via the destructuring of the opts variable.

**Comment by charleshansen** [comment]
It should all be there in 8.3.0
