### ISSUE TITLE
Additional currency icons 

### ISSUE THREAD

**Issue by PivotNeilTarrant** [pivotal-cf/pivotal-ui#510]
We're using the 'Input' component (https://styleguide.cfapps.io/react_components_forms.html#00_form_input_react) with a currency symbol as the icon for currency fields in our app. 

Currently we've obtained SVGs of the required currency symbols (£, $, €, ¥), but having stylistically consistent icons for each would be useful.

**Comment by charleshansen** [comment]
Sounds like a great idea, @elliotdahl should be handling this sometime.

**Comment by mingxiao** [comment]
I've created a story to track this feature request, https://www.pivotaltracker.com/story/show/150556334

**Comment by sjolicoeur** [comment]
@PivotNeilTarrant is this still an issue for you?

**Comment by PivotNeilTarrant** [comment]
It would still be useful for our project but it is not a high priority for us.

**Comment by reid47** [comment]
@PivotNeilTarrant Since this is no longer a high priority for your team, and since it's possible to just use text instead of SVGs, we are going to close this issue. Feel free to reopen it if you need more from us.
