### ISSUE TITLE
Select styling is reliant on lists CSS

### ISSUE THREAD

**Issue by davidje13** [pivotal-cf/pivotal-ui#512]
The `margin-top` property of the `<ul>` tag used by `Select` is not specified by Select's own CSS. This means that on pages which use `Select` but not `List`, there is a noticable gap between the select body and the dropdown list.

**Comment by charleshansen** [comment]
Good catch, we'll add the dependency

**Comment by davidje13** [comment]
Confirmed fixed in 8.3.0
