### ISSUE TITLE
Regression in 8.2.0: Select content is misaligned

### ISSUE THREAD

**Issue by davidje13** [pivotal-cf/pivotal-ui#513]
The select element's disclosure indicator is misaligned in the latest release. This can be seen in the documentation: https://styleguide.cfapps.io/react_components_select.html

The disclosure previously was right-aligned and vertically centred, but is now positioned just after the label and vertically at the bottom of the container. Also the label text appears to be centred rather than left aligned.

**Comment by charleshansen** [comment]
Thanks for the catch, and with really easy reproduction :) We'll look into the fix.

**Comment by davidje13** [comment]
Confirmed fixed in 8.3.0
