### ISSUE TITLE
pui-react-overlay-trigger or pui-react-tooltip is not sticky when isSticky={true}

### ISSUE THREAD

**Issue by tmpg** [pivotal-cf/pivotal-ui#516]
Hey all,

Thanks for the lib. I have been wanting to use pui-react-overlay-trigger with sticky on. I want to do something similar to Facebook where u hover and then the tooltip pops up and you can hover over the tooltip but it does not seem to be working with pui-react-overlay-trigger or pui-react-tooltip.

Anyone have any suggestions?

**Comment by elenasharma** [comment]
Hello @tmpg,

Thanks for bringing this issue to our attention. We will get to work on fixing it.

**Comment by tmpg** [comment]
@elenasharma was this a confirmed bug?

**Comment by elenasharma** [comment]
@tmpg yes, we confirmed it yesterday. It works with TooltipTrigger, but not the other two components.

**Comment by tmpg** [comment]
Not to be too demanding but is there an ETA? Just curious.

**Comment by charleshansen** [comment]
I'm not entirely sure, but my guess is a couple weeks. If this is really blocking development for your project, let us know.

**Comment by tmpg** [comment]
No not at the moment. In a month or so it will be. I am just keeping an eye on it. Thanks again!

**Comment by successivesoftware** [comment]
Hi, I am having the same issue, please let me know ETA if possible. Thanks

**Comment by tmpg** [comment]
How is this looking?

**Comment by charleshansen** [comment]
Should be very soon

**Comment by tmpg** [comment]
thanks for keeping on top of it!

**Comment by charleshansen** [comment]
8.3.2 was just published, the fix should be there.
