### ISSUE TITLE
Select's onChange is inconsistent with other form input types

### ISSUE THREAD

**Issue by davidje13** [pivotal-cf/pivotal-ui#518]
The `Select` element's `onChange` passes a parameter of the updated `value` for the select. This is inconsistent with HTML input types and Pivotal UI's other input types.

It would be more convenient when wrapping components if this was made consistent. As a minimum, it would be helpful if the value was provided in a simple wrapper such as `{target: {value: <value_here>}}`, but ideally it should be passed a real event object.

Clearly this would be a breaking change, so would probably need to be part of a major version bump.

**Comment by charleshansen** [comment]
Good call, I'll prioritize a fix. We can pass along the click event, but inject value into `target` and `currentTarget`.

Since this is a breaking change, you might not see it for a little bit. We usually accumulate a few breaking changes before doing a major bump.

**Comment by mingxiao** [comment]
The corresponding tracker story: https://www.pivotaltracker.com/story/show/147567637
Fix commit: https://github.com/pivotal-cf/pivotal-ui/commit/488fea2afdff8fa83c3d24f3dcac0034562178a1

Will be in PUI 9 release
