### ISSUE TITLE
scrim error for SVG element on IE11

### ISSUE THREAD

**Issue by ryascl** [pivotal-cf/pivotal-ui#519]
Using pui-react-overlay-trigger on an SVG element in IE 11.0.9600, we get spammed with error 'Object doesn't support property or method 'contains'', originating at scrim_mixin.js:6 . This is due to the fact that SVGTextElement does not have contains() function.

In other browsers, tooltip works fine on an SVG element.

https://github.com/pivotal-cf/pivotal-ui/blob/master/library/src/pivotal-ui-react/mixins/mixins/scrim_mixin.js#L6

Observed on versions 7.5.5 and 8.3.1.

**Comment by charleshansen** [comment]
Interesting. We'll look into it.

**Comment by charleshansen** [comment]
We have a fix that should be in the next release

**Comment by ryascl** [comment]
Thanks for the update, @charleshansen . 
FYI, SVGSVGElement also lacks contains() function.
We had to monkey-patch that as well to get things working.

**Comment by charleshansen** [comment]
Good to know. The fix should hopefully handle anything that does not have the contains function.

**Comment by jberney** [comment]
The error has been fixed in **v8.3.2**.
