### ISSUE TITLE
Incorrect NPM package name for React form components

### ISSUE THREAD

**Issue by loktar** [pivotal-cf/pivotal-ui#524]
We were trying to use `https://styleguide.pivotal.io/forms` in our app, and the NPM package that we are told to install in the `Installation & Usage` section is `pui-react-forms`, but this doesn't exist on NPM.

The correct package for the component we needed (the search bar) is `pui-react-inputs` according to @rdy. 

This may need to also be fixed in other locations.

**Comment by jberney** [comment]
We fixed the issue and it will be live in the next deploy.
