### ISSUE TITLE
Disable out-of-scope styling

### ISSUE THREAD

**Issue by slipperypenguin** [pivotal-cf/pivotal-ui#529]
When trying to integrate the [Select Component](https://styleguide.pivotal.io/select) into my existing react-app, many other component styles get overwritten when `import {Select} from 'pui-react-select';` is called.

In my case, the `<Select/>` component is created as intended, but all of my button components that are not through pivotal-ui are resized and all over the place.

Is there a way to disable this extra styling from overwriting other components?

**Comment by sjolicoeur** [comment]
We usually think of Pivotal-UI as being an all-in type of library, meaning you should also be using our other components. You cannot disable styling other components with Pivotal UI.

That said, our CSS selectors can overwritten by the same rules or more targeted ones. An easy fix to try is to make sure you load `import {Select} from 'pui-react-select';` before you load any of your other styling so they can override any pivotal-ui styling.
