### ISSUE TITLE
Tooltip should not propagate upwards when triggered by click

### ISSUE THREAD

**Issue by sqren** [pivotal-cf/pivotal-ui#530]
I'm running into an issue where several click handlers are affected, when the TooltipTrigger is placed inside another clickable element:

```jsx
<div onClick={() => alert('You clicked the outer div')}>
   Hello
    <TooltipTrigger tooltip="Some tooltip" trigger="click">
      <button className="btn btn-default">Click me</button>
    </TooltipTrigger>
</div>
```

When clicking anywhere but on the tooltip the outer click handler fires. However, when clicking the tooltip button, both the inner and the outer click handler fires. I can normally fix this with `e.stopPropagation`:

```jsx
<div onClick={() => alert('You clicked the outer div')}>
   Hello 1
    <div onClick={e => {
        e.stopPropagation();
        alert('You clicked the inner div');
    }}>Click me</div>
    </div>
</div>
```

How can I achieve the same with pui tooltip?
Thanks!

**Comment by sjolicoeur** [comment]
Well, as of right now you cannot... but we will implement a fix for this by allowing you to provide your own onClick function as to supplement the default one. As such you'll be able to stop the propagation of the event if you so desire.

**Comment by jberney** [comment]
Our fix was to allow an onClick handler to be passed to the TooltipTrigger. The onClick handler will be called right after we make the tooltip visible. The onClick event is made available, so the user can call stopPropagation, preventDefault, etc.

Our plan is for this fix to be available in PUI v9.

**Comment by charleshansen** [comment]
The future version of TooltipTrigger is the best solution in the long run, but in the meantime, you can always hack it to not call the outer alert. I haven't tried the actual code, but it would look vaguely like this (you might need to use React `ref`s on the TooltipTrigger or the button instead of checking the classList)

```
<div onClick={(e) => {if(!e.target.classList.includes('tooltip')) alert('You clicked the outer div')}}>
   Hello 1
    <TooltipTrigger tooltip="Some tooltip" trigger="click">
      <button className="btn btn-default">Click me</button>
    </TooltipTrigger>
    </div>
</div>
```

**Comment by sqren** [comment]
Thanks for the help. Looking forward to PUI v9!
