### ISSUE TITLE
Proposed Tooltip changes

### ISSUE THREAD

**Issue by ahuth** [pivotal-cf/pivotal-ui#536]
Currently we're using the Tooltips, and the TooltipTrigger meets our needs better than the OverlayTrigger. However, we need the ability to manually control visibility of the tooltip programmatically, like the OverlayTrigger.

If I make a PR adding that, is that something you'd be willing to accept?

**Comment by ahuth** [comment]
cc @roblevintennis @juanca

**Comment by roblevintennis** [comment]
* Bump * It's helpful for us to know whether this has a chance to get in. If not, and we do this, we're stuck pointing to a forked#branch :) Seems like the tooltip and overlay versions having a constent programmatic interface would be a good thing though no?

**Comment by charleshansen** [comment]
A PR sounds good. It would be better for OverlayTrigger and TooltipTrigger to be more aligned.

There isn't a good reason TooltipTrigger doesn't have manual control. Traditionally, people who need manual control also need other features from OverlayTrigger, so it hasn't been a priority.

**Comment by ahuth** [comment]
Implemented the change in #539.

**Comment by ahuth** [comment]
@reid47 @charleshansen Any word on when we can expect #539 to be published?

**Comment by reid47** [comment]
@ahuth These changes have just been published in v10.3.1! Thanks for your help.

**Comment by ahuth** [comment]
Ah, gotcha. @reid47, when do the per-component packages get updated? Referring specifically to https://www.npmjs.com/package/pui-react-tooltip, which is at v8.3.3.

**Comment by reid47** [comment]
@ahuth Since the v9 release, Pivotal UI has become one package containing all of our components. Please see the "PUI 9.0 Release" section in our [upgrade guide](https://styleguide.pivotal.io/upgradeguide) for details; you'll need to install the `pivotal-ui` package and use the tooltip components like this:
```
import {Tooltip, TooltipTrigger} from 'pivotal-ui/react/tooltip';
```

**Comment by ahuth** [comment]
Gotcha. Thanks!
