### ISSUE TITLE
PUI CSS flex grid should not use nested CSS for .col

### ISSUE THREAD

**Issue by rdy** [pivotal-cf/pivotal-ui#538]
## What version of Pivotal UI are you using?
9

## What behavior are you seeing?
The CSS for `.col` is nested under `.grid` this prevents us from extending using our own classes. We'd like to see almost all the CSS in PUI to not nest where possible, we should very sparingly use nesting so people can use tools like CSS modules.

## What do you expect to see?
The `.col` class should have top level CSS, its slower and unnecessary to nest it.

**Comment by jberney** [comment]
Hi Ryan,

Sorry for the delay. This work is now prioritized in our backlog. We'll probably get to it in early January.

**Comment by reid47** [comment]
This fix has been back ported to v12, published as 12.1.1.
