### ISSUE TITLE
Links should not force SVG fill color to be blue

### ISSUE THREAD

**Issue by rdy** [pivotal-cf/pivotal-ui#540]
## What version of Pivotal UI are you using?
9
## What behavior are you seeing?
Any svg inside a link is modified by the rule `a svg` which comes from links.css

## What do you expect to see?
We should not expect the fill color of all links to be blue, if we need this behavior it should be a behind a class rather than the global selector.

**Comment by jberney** [comment]
Hi Ryan,

Sorry for the delay. This work is now prioritized in our backlog. We've also recently been affected by this issue in Apps Manager. We'll probably get to investigating this in early January.

**Comment by reid47** [comment]
@rdy We have a [fix](79e5bc96f7d5a0c8fcde53ac15f56dee62285115). Since this is a breaking change, it will be in the next major version of PUI (v13).
