### ISSUE TITLE
Pivotal-Ui should internalize external node_module forks

### ISSUE THREAD

**Issue by rdy** [pivotal-cf/pivotal-ui#541]
## What version of Pivotal UI are you using?
10.2

## What behavior are you seeing?
When pushing an app that depends on pivotal-ui (offline) it can't pull in the external react-tether dependency because it doesn't understand external forks.

## What do you expect to see?
If the dependency was vendored in Pivotal-ui itself our app would be able to push offline.

**Comment by mingxiao** [comment]
Hello @rdy, thank you for raising this issue.

You can track the progress of this issue via https://www.pivotaltracker.com/story/show/152859677

**Comment by sjolicoeur** [comment]
@rdy this work has been [done](https://github.com/pivotal-cf/pivotal-ui/commit/005d642d7ecbf14e25aaf5c2a29025853013df70)!
