### ISSUE TITLE
Modal close button should have a button type="button"

### ISSUE THREAD

**Issue by weymanf** [pivotal-cf/pivotal-ui#542]
## What version of Pivotal UI are you using?
10

## What behavior are you seeing?
When you close a modal, the onHide for the button (x icon) is treated as a form which does not make sense. The type of the button should be button  otherwise you MUST specify prevent default for onHide function which is strange.

## What do you expect to see?
`<button type="button">` for the close button (x icon)

**Comment by sjolicoeur** [comment]
@weymanf this will be fixed in `v11.1`
