### ISSUE TITLE
SortableTable should allow users to turn off the sort order none option when sortable is set to true.

### ISSUE THREAD

**Issue by peterhaochen47** [pivotal-cf/pivotal-ui#543]
## What version of Pivotal UI are you using?
10
## What browser and version are you using?

any browser

## What behavior are you seeing?

When toggling sort desc and asc, there is a third option which turns off sorting. 

## What do you expect to see?

We want the ability to make the sorting just a toggle between asc and desc. And not have the off mode.

**Comment by jberney** [comment]
Hi Peter,

This work is now prioritized in our backlog, we'll probably get to investigating this in early January. Let's cross-team pair with Metrics so that your team can gain context on PUI table plugins. We'll come by and ask about availability on your team when we pick this issue up.

**Comment by mingxiao** [comment]
@peterhaochen47 when you guys want to cross team pair, please reach out to us.
