### ISSUE TITLE
Tab: Mouseover field is always displayed

### ISSUE THREAD

**Issue by mjj209** [pivotal-cf/pivotal-ui#545]
**Steps to Reproduce**
Mouseover the area of a tab for 3 seconds or longer

**Expected**
Display curser text when the object the curser is over needs to be explained. 

**Result**
Curser text is always displayed. This leads to covering up other text on the page which is potentially important. This is also distracting to the end user.
![img_1295](https://user-images.githubusercontent.com/18425603/33635735-02f35b54-d9ce-11e7-9e69-6b5caf06de11.JPG)

**Comment by jberney** [comment]
Hey Mike,

We've prioritized this issue in our backlog, and will probably get to it in January. Which version of PUI is your team using? This way we know how far we should backport the fix.

Thanks!

**Comment by reid47** [comment]
@mjj209 Which version of PUI is your team using?

**Comment by mingxiao** [comment]
@mjj209 the fix is in Pivotal-UI v13.0.1

**Comment by klakin-pivotal** [comment]
@reid47 @jberney Sorry for the delay. We're using PUI v13.0.x (`"pivotal-ui": "^13.0`) , so it looks like no backporting was required.
