### ISSUE TITLE
Can't resolve '../../../../app/svgs' 

### ISSUE THREAD

**Issue by hutber** [pivotal-cf/pivotal-ui#549]
Thanks for making these, I've just noticed a whole load of erros in my console, thought I would flag it for you.

## What version of Pivotal UI are you using?
9.2.0

## What browser and version are you using?
Chrome 64

## What behavior are you seeing?
````
WARNING in ./node_modules/pivotal-ui/react/iconography/iconography.js
Module not found: Error: Can't resolve '../../../../app/svgs' in '/var/www/web/frontend/node_modules/pivotal-ui/react/iconography'
 @ ./node_modules/pivotal-ui/react/iconography/iconography.js 58:17-245
 @ ./node_modules/pivotal-ui/react/iconography/index.js
 @ ./src/components/Nav/index.jsx
 @ ./src/components/index.jsx
 @ multi babel-polyfill ./src/components/index.jsx webpack/hot/only-dev-server
````

## What do you expect to see?
No errors

**Comment by StevenLocke** [comment]
Hi @hutber,

This issue should be solved in v9.2.1
If the problem persists, please let us know.
