### ISSUE TITLE
CopyToClipboard Icon is grey in forms

### ISSUE THREAD

**Issue by squeedee** [pivotal-cf/pivotal-ui#550]
## What version of Pivotal UI are you using?
12.1.0

## What browser and version are you using?
chrome.. ish

## What behavior are you seeing?
CopyToClipboard Icon is grey when in a form

## What do you expect to see?
White :)

Jonathan Berney has seen this in action

```
   <Form>
            <FormRow>
                <FormCol inline label="URL">
                    <Input value={environment.opsmgr.url} readOnly className="col"/>
                    <CopyToClipboard text="{environment.opsmgr.url}" className="type-neutral-11 col col-fixed">
                        <PrimaryButton {...{
                            iconOnly: true,
                            icon: <Icon src="copy"/>
                        }}/>
                    </CopyToClipboard>
                </FormCol>
            </FormRow>
   </Form>
```

**Comment by mingxiao** [comment]
@squeedee the fix is published in 14.0.0.

Let us know if it needs to be backported and we'll try our best to accomodate
