### ISSUE TITLE
CopyToClipboard does not copy newlines

### ISSUE THREAD

**Issue by squeedee** [pivotal-cf/pivotal-ui#551]
## What version of Pivotal UI are you using?
12.1
## What browser and version are you using?
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

## What behavior are you seeing?
CopyToClipboard loses newlines

## What do you expect to see?
newlines.. specifically I'm presenting a ssh key

**Comment by squeedee** [comment]
```
const cp = "hello\nthere"
return <div className="copy-input grid">
  <textarea readOnly className="col">{cp}</textarea>
  <div className="col">
    <CopyToClipboard text={cp}>
      <PrimaryButton {...{
        iconOnly: true,
        icon: <Icon src="copy"/>
      }} />
    </CopyToClipboard>
  </div>
 </div>
```

**Comment by reid47** [comment]
Fixed in master. We will get this fix into the next patch release of PUI 12 and up.

**Comment by mingxiao** [comment]
The fix has been backported to versions 12 and up.
