### ISSUE TITLE
textarea has a set height (with forms imported)

### ISSUE THREAD

**Issue by squeedee** [pivotal-cf/pivotal-ui#552]
## What version of Pivotal UI are you using?
12.1

## What browser and version are you using?
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

## What behavior are you seeing?
textarea elements have a set height if i import forms, see https://github.com/pivotal-cf/pivotal-ui/blob/master/src/css/forms/forms.scss#L10

## What do you expect to see?
The textarea should follow my rows attribute

```
<textarea readonly="" rows="5" class="col">
Hi There! 
Line2 
Line3 
Line4
Line5
</textarea>
```

**Comment by reid47** [comment]
The desire is for pivotal-ui provide reasonable defaults for styling form elements. We've decided not to change the default height for textareas.

You can override the default with `height: initial` on the `<textarea>`.
