### ISSUE TITLE
fix(Tabs): description

### ISSUE THREAD

**Issue by Camilo-HG** [pivotal-cf/pivotal-ui#553]
**Steps to Reproduce**

I included module:

    import {Tabs, Tab, LeftTabs} from 'pivotal-ui/react/tabs';

Then I copied example:

    <div>
       <Tabs defaultActiveKey={1} actions={<a>Action!</a>}>
         <Tab eventKey={1} title="Tab 1">Wow!</Tab>
           <Tab eventKey={2} title="Tab 2">
             <h2>Neat!</h2>
             <span>So much content.</span>
         </Tab>
       </Tabs>
    </div>

**Expected**
Tabs should look as in the example

**Result**
![tabs_error](https://user-images.githubusercontent.com/22363097/35682928-615bed20-0730-11e8-98b9-72f7dec328d2.png)

**Comment by Camilo-HG** [comment]
Version 13.0.1 
Browser: Chrome

**Comment by reid47** [comment]
@Camilo-HG Thanks, we have reproduced the issue and have a fix for it. It will definitely go into PUI 15, but we will update and close this issue when we know which previous versions of PUI will be updated with this fix.

**Comment by mingxiao** [comment]
@Camilo-HG This is fixed and published in 14.0.0.

Let us know if you need this in an earlier version, we will try our best to accomodate.
