### ISSUE TITLE
collapse Collapse component programmatically?

### ISSUE THREAD

**Issue by dubstylee** [pivotal-cf/pivotal-ui#560]
I am wondering if there is a way to programmatically collapse a Collapse component. I know that you can set the defaultExpanded property to false when rendering the component to collapse it by default, but I am hoping to trigger a collapse based on a state change on the parent component. Is this possible? I am already modifying the Collapse header property on a state change, but cannot get the Collapse to collapse except by clicking on the header.

## What version of Pivotal UI are you using?
15.0.0
## What browser and version are you using?
Version 65.0.3325.181 (Official Build) (64-bit)
## What behavior are you seeing?
Can only collapse element manually.
## What do you expect to see?
Would like to be able to collapse an element programmatically.

**Comment by reid47** [comment]
Hi @dubstylee,

Our `Collapse` component is somewhat limited/opinionated in how it works, as you're noticing. I think that you'll be able to achieve the effect you're going for by using our `Collapsible` or `ExpanderContent` components instead.

For an example, see the one here: https://styleguide.pivotal.io/collapsible

The `Collapsible` just takes an `expanded` prop, which will come from somewhere outside the component (for example, in the state of the parent component, as shown in that example). Then you can update this value however you want.

Please let us know if you're still unable to achieve what you're going for!

**Comment by dubstylee** [comment]
@reid47 

Excellent, I do believe that `ExpanderContent` will work for what I'm looking for. `Collapsible` didn't have the flexibility I was hoping for, but it looks like `ExpanderContent` can do everything I need. Thanks for the info!
