### ISSUE TITLE
Autocomplete - showNoSearchResults prop doesn't work

### ISSUE THREAD

**Issue by weymanf** [pivotal-cf/pivotal-ui#561]
## What version of Pivotal UI are you using?
15

## What browser and version are you using?
Chrome

## What behavior are you seeing?
The words 'No search results' is not showing up on the `autocomplete` component.

## What do you expect to see?
The words to show up when the flag (showNoSearchResults ) is true

**Comment by mingxiao** [comment]
We could not reproduce this issue, please include a valid example that demonstrates the bug.
