### ISSUE TITLE
Code Syntax Highlighting when using create-react-app

### ISSUE THREAD

**Issue by mcnichol** [pivotal-cf/pivotal-ui#564]
## What version of Pivotal UI are you using?
**pivotal-ui": "^16.0.0",**

## What browser and version are you using?
**Version 66.0.3359.181 (Official Build) (64-bit)**

## What behavior are you seeing?
In using: create-react-app, issues with syntax highlighting

<img width="556" alt="screen shot 2018-06-14 at 9 34 04 pm" src="https://user-images.githubusercontent.com/7227690/41447409-bbd95aaa-701a-11e8-8a9e-c352c3a3a98d.png">

## What do you expect to see?
<img width="469" alt="screen shot 2018-06-14 at 9 29 11 pm" src="https://user-images.githubusercontent.com/7227690/41447261-0e345512-701a-11e8-8cd0-87715bac50ed.png">

Before we immediately close this because webpack is a factor in this picture, I'd suggest we consider the relevance and importance of quickly building CRA front-ends for greater adoption and speed.  CRA offers considerable value and would be worth having a better integration story.

**Comment by reid47** [comment]
Hi @mcnichol, thanks for filing this issue! We definitely agree that CRA is an important and valuable tool, and we want to do what we can to make Pivotal UI work seamlessly with it.

We also are aware that syntax highlighting with Prism is somewhat tricky to set up with Pivotal UI. I think we can do more to make this easier to integrate. Can you give us a little more info about how you're doing it? Were you following instructions from the Pivotal UI styleguide and/or the Prism documentation?

**Comment by reid47** [comment]
Hi @mcnichol, are you still having this problem? If so, can you tell us a little more about how you're importing Prism (e.g. is it just through `script`/`style` tags, or are you importing it into JS files via Webpack?). If this isn't still a problem, can we close this issue? Thanks!

**Comment by mcnichol** [comment]
I was able to import through script/style tags and ultimately resorted to controlling prism myself. A few ways to do it but something each user could decide on how they solve.

Will close.
