### ISSUE TITLE
vAlign top for Media

### ISSUE THREAD

**Issue by pnikonowicz** [pivotal-cf/pivotal-ui#566]
## What version of Pivotal UI are you using?
17.0.0

I would like to specify the following:

```
<Media vAlign='top' />
```

Currently this is the default behaviour, but it is not obvious when looking at this component in an developers environment. 

I would like the `top` attribute to be valid one and not give a proptype error.

**Comment by sweinstein22** [comment]
Hi @pnikonowicz,

We have made this change in master (allowing you to pass `vAlign="top"` without a warning, though it doesn't affect the behavior of the component). Would you like us to backport this to v17 and do a patch release?

**Comment by jberney** [comment]
We've released a fix for this issue in PUI 17.0.2.

**Comment by reid47** [comment]
I'm going to close this issue, since we have released a fix. Feel free to reopen it if you feel this wasn't fully addressed!
