### ISSUE TITLE
update pui-react-overlay-trigger npm package

### ISSUE THREAD

**Issue by bj00rn** [pivotal-cf/pivotal-ui#567]
Update pui-react-overlay-trigger npm package was last updated a year ago. Are there any plans for a new release anytime soon?

**Comment by charleshansen** [comment]
All of the separate pui components are now part of the `pivotal-ui` npm package. For a more recent release, you would import the overlay trigger directly from `pivotal-ui`:
```js
import {OverlayTrigger} from 'pivotal-ui/react/overlay-trigger';
```

**Comment by bj00rn** [comment]
@charleshansen awesome, thanks!

**Comment by bj00rn** [comment]
maybe there should be a message on npm for packages that have been deprecated?

**Comment by reid47** [comment]
@bj00rn I think that's a good idea. I'll do that for our `pui-react-*` and `pui-css-*` packages.
