### ISSUE TITLE
AdvancedTable - Sort + Drawer

### ISSUE THREAD

**Issue by ksmith-taos** [pivotal-cf/pivotal-ui#570]
## What version of Pivotal UI are you using?
17.0.2

## What browser and version are you using?
Version 69.0.3497.100 (Official Build) (64-bit)

## What behavior are you seeing?
Using the Sorting Plugin and Row Drawer Plugin together does not sort the Row Drawer, only the rows.
Using the AdvancedTable has the same issues.

![selection_006](https://user-images.githubusercontent.com/41973121/46163344-ccd46580-c23f-11e8-936a-c3d405e5228f.png) 
```
const TableWithRowDrawer = withRowDrawer(withSorting(FlexTable));
const columns = [1, 2, 3].map(n => ({
  attribute: `header${n}`,
  sortable: true,
  displayName: `Header ${n}`
}));

const data = ['A', 'B'].map(row => ({
  header1: row,
  header2: row,
  header3: row,
  drawerContent: row
}));

const rowDrawer = i => (
  <div className="table-drawer">
    <div className="table-drawer-content">
      <div className="table-drawer-container phxl">
        {data[i].drawerContent}
      </div>
    </div>
  </div>
);

<div>
    <TableWithRowDrawer columns={columns} data={data} rowDrawer={rowDrawer}/>
    <AdvancedTable columns={columns} data={data} rowDrawer={rowDrawer}/>
</div>
```

## What do you expect to see?
It is expected that the Row Drawers would sort as well.

**Comment by reid47** [comment]
Hi @ksmith-taos, thanks for the report. We are able to reproduce this issue and have filed a bug in our backlog.

**Comment by reid47** [comment]
Hi @ksmith-taos, we found the issue was in our example and have updated it accordingly. If you take rowDatum as a second argument to the rowDrawer function, and use that instead of data[i] to get the drawerContent the table should work as expected.

```
const rowDrawer = (i, rowDatum) => (
  <div className="table-drawer">
    <div className="table-drawer-content">
      <div className="table-drawer-container phxl">
        {rowDatum.drawerContent}
      </div>
    </div>
  </div>
);
```

**Comment by ksmith-taos** [comment]
Nice. Thank you for finding that so quickly.

**Comment by sweinstein22** [comment]
I'm glad we could help! I'm going to close this issue, feel free to reopen it if you find this wasn't fully addressed.
