### ISSUE TITLE
'print' icon SVG has hard-coded fill value

### ISSUE THREAD

**Issue by mingxiao** [pivotal-cf/pivotal-ui#579]
## What version of Pivotal UI are you using?

17.0.4

## What behavior are you seeing?

The 'print' icon is always filled with black (`#000000`) because the `fill` attribute is hard-coded on the `svg` tag.

## What do you expect to see?

We should be able to control the fill color from the outside (like from the `Icon` component), but we can't do that if it's hard-coded like this.

**Comment by reid47** [comment]
We have released v17.1.2, which fixes this problem (and also fixes the same problem in the `highlight` icon).
