### ISSUE TITLE
Component request: Pivotal Siteframe

### ISSUE THREAD

**Issue by jberney** [pivotal-cf/pivotal-ui#580]
Hello Pivotal UI team!

The App SSO team is writing a new frontend app using Pivotal UI, and we would like to use a Siteframe component similar to what Apps Manager has. We are mainly interested in a header that gives us:
  * A logo that we can click to get back to "home". We're probably going to use React Router, so hopefully whatever routing solution we come up with for the PUI component can work with this.
  * An app title (it will be hardcoded to "Single Sign-On")
  * Customizable content (we may want to show the user's current org and space, but maybe we also show this below the Siteframe header instead)
  * Account dropdown on the right (shows the user you're logged in as, dropdown has a "sign out" option)

We don't currently need a sidebar, so it would be good if that is optional.

We have similar footer requirements to Apps Manager (copyright, privacy policy, terms of use, optional GDPR cookie link), and it would be great if a Siteframe component could do some of this for us as well.

For the time being, we stole the Siteframe component directly from Apps Manager. We found a few problems, but were able to work around them (listing them here so you know a few things to look out for):
  * `header.js` is pointing directly to Apps Manager features (RoutesHelper and Anchor)
  * `siteframe.scss` is using some Apps Manager specific sass variables (e.g. `$body-text-color`, I believe there are a few others)

Thanks!

**Comment by StevenLocke** [comment]
We on the Security Triage team have a very similar need, and we made due with a very similar solution.  Take this as a +1 to this request.

**Comment by reid47** [comment]
We've released this in v17.1.0. Please give it a try and let us know if it doesn't meet your needs! Thanks!

Going to close this issue, but feel free to reopen it or file another if you'd like us to make changes to it.
