### ISSUE TITLE
Siteframe component feature request: title link

### ISSUE THREAD

**Issue by jberney** [pivotal-cf/pivotal-ui#583]
Hello Pivotal UI team from App SSO!

Our team's designer has requested the ability to make the Siteframe title text link to a "home" location for our app. Currently, the Siteframe component has the `companyName` and `productName` props, but they are both strings, so we can't wrap the values in a link component without getting development warnings.

We're open to whatever solution you all think is best. Some possibilities:
* Company/product names could be nodes instead of strings, which would allow us to wrap them in link components of our choosing.
* There could be a new link prop that wraps the company/product names (maybe the logo too?)
* Maybe we could pass nothing for companyName/productName, and do all of the rendering ourselves in the `cols` props. I think this isn't ideal because our title will look inconsistent when the way Pivotal UI renders its title changes.

I think none of these solutions are breaking changes. We're open to other solutions as well.

Thanks!

**Comment by mingxiao** [comment]
Hello App SSO from Pivotal UI!

Thanks for the request! I'm leaning towards the first option.

Our original decision to keep `companyName` and `productName` as separate props, instead of being a user defined column, was to be opinionated about the layout.

**Comment by reid47** [comment]
I'm wondering if this is another case where our Siteframe could enforce consistency across products.

In Apps Manager, the logo in the header is a link that takes you to the home page, but the header text is not a link.

Maybe our designers should chat about which pattern we prefer, and then we could bake it into the Siteframe so both teams would use it?

**Comment by jberney** [comment]
@mingxiao fyi I noticed that when wrapping `productName` in an anchor tag, it gets the PUI link blue color. Here's the css that fixed the color for me, but feel free to fix it in PUI however you all would like (e.g. could set the color to the same color variable as the header text):
```
.pui-siteframe-header a {
  color: inherit;
}
```

**Comment by reid47** [comment]
@jberney We have just released v17.1.2 which addresses the issues above (`companyName` and `productName` are now nodes, not strings, and we included the CSS you suggested). Closing this issue, but feel free to reopen/make another for more changes.
