### ISSUE TITLE
sandbox does not work from fresh clone

### ISSUE THREAD

**Issue by mingxiao** [pivotal-cf/pivotal-ui#589]
## What version of Pivotal UI are you using?
master branch
## What browser and version are you using?
n/a
## What behavior are you seeing?
reproduction steps:
1. get fresh clone of `pivotal-ui`
1. cd sandbox
1. yarn
1. yarn start

Seeing this error:
```
Cannot destructure property `compile` of 'undefined' or 'null'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## What do you expect to see?

A 'hello world' app

**Comment by reid47** [comment]
Hi @mingxiao, just upgraded a bunch of things and this should work now in the master branch.

Verified that the following works for me:

```
git clone https://github.com/pivotal-cf/pivotal-ui.git
cd pivotal-ui
yarn
cd sandbox
yarn
yarn create-sandbox
yarn start
```

Note the new `yarn create-sandbox` line. This just creates a simple `sandbox.js` file for you (which is where you'll make your changes while developing).

Going to close this now, but let me know if this doesn't work for you!
