### ISSUE TITLE
Please update source sans pro font to a newer version that has Cyrillic support 

### ISSUE THREAD

**Issue by funcode** [pivotal-cf/pivotal-ui#630]
**Is your feature request related to a problem? Please describe.**
When we do localization for Russian, it seems that the Cyrillic glyphs are not rendered with source sans pro font, but fall back to the sans-serif font setting of the browser.

**Describe the solution you'd like**
It seems the source sans pro shipped with Pivotal UI doesn't contain Cyrillic support. This can be told by comparing the font file size with those on Adobe's git repo.

**Comment by sweinstein22** [comment]
Hi @funcode , we've added a story in our backlog to complete this, though the tracker project is private so you may not be able to see the details: https://www.pivotaltracker.com/story/show/168033824

We appreciate your patience and will work on updating the files soon.

**Comment by sphawley** [comment]
Hey @funcode,  pivotal-ui v18.1.2 has support for Cyrillic glyphs!

**Comment by funcode** [comment]
@sphawley Thanks for the quick fix! We will try it out.

**Comment by sweinstein22** [comment]
I'm going to close out this issue, feel free to reopen it if you find the problem has not been solved. Thanks!
