### ISSUE TITLE
How to create PCF new Service with Certificate instead of Client-Key?

### ISSUE THREAD

**Issue by jainath23** [pivotal-cf/pivotal-ui#657]
{
  "uri": "https://akv-xxx-dev.vault.azure.net/",
  "clientId": "d8472266-xxx-xxx-934f-xxx",
  "clientKey": "xxxxxx",
  "tenantId": "xxxxx-55b6-466e-a7af-4ad1a1b79713"
}

How to create PCF new Service with Certificate instead of [Client-Key?]

**Comment by reid47** [comment]
Hi @jainath23, thanks for reaching out, but this does not appear to be an issue with Pivotal UI (the React component library). Perhaps you meant to file this issue in a different repo?

I'm going to close this issue, but please reopen it if I'm missing something!
